version: "3.4"
services:
  homeassistant:
    image: homeassistant/home-assistant:2025.10
    restart: unless-stopped
    volumes:
      - ./volumes/homeassistant/config:/config
    depends_on:
      - mosquitto
      - zigbee2mqtt
    environment:
      - TZ=America/Montreal
    ports:
      - 8123:8123

  tasmoadmin:
    image: raymondmm/tasmoadmin
    volumes:
    - ./volumes/tasmoadmin/data:/data
    ports:
    - 9003:80

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.35.2
    # Was 1.25.1
    privileged: true
    restart: always
    depends_on:
      - mosquitto
    volumes:
      - ./volumes/zigbee2mqtt/data:/app/data
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /run/udev:/run/udev:ro
    environment:
    - TZ=America/Montreal

  mosquitto:
    image: ansi/mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    entrypoint: /usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
    volumes:
      - ./volumes/etc/mosquitto:/etc/mosquitto:ro
      - ./volumes/var/log/mosquitto:/var/log/mosquitto:rw
      - ./volumes/var/lib/mosquitto/mosquitto.db:/var/lib/mosquitto/mosquitto.db:rw
    environment:
      - TZ=America/Montreal

  cloud9: # https://hub.docker.com/r/sapk/cloud9/
    image: linuxserver/cloud9
    restart: unless-stopped
    privileged: true
    volumes:
    - ./:/code/homeassistant
    - ~/code/wireguard:/code/wireguard
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - PGID=1000
    # - PUID=99
    - TZ=America/Montreal
    - GITURL=https://github.com/linuxserver/docker-cloud9.git
    ports:
    - "8000:8000"

  logs:
    image: gerchardon/docker-logio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -h logio -n docker
    depends_on:
      - logio
    restart: no

  logio:
    image: temal/logio-server
    restart: no
    ports:
      - 9002:28778

  zoneminder:
    image: zoneminderhq/zoneminder:latest-ubuntu18.04
    restart: unless-stopped
    volumes:
     - /mnt/sdb1/zoneminder/events:/var/cache/zoneminder/events
     - /mnt/sdb1/zoneminder/images:/var/cache/zoneminder/images
     - /mnt/sdb1/zoneminder/mysql:/var/lib/mysql
     - /mnt/sdb1/zoneminder/logs:/var/log/zm
    devices:
     - /dev/video0:/dev/video0
     - /dev/video1:/dev/video1
    shm_size: 4gb
    ports:
      - 1080:80
    environment:
     - TZ=America/Montreal
    labels:
     - "traefik.http.routers.zoneminder.rule=Host(`zm3.f1961.nmac.com.ar`)"
     - "traefik.enable=true"
     - "traefik.http.routers.zoneminder.tls.certresolver=lets-encr"
     - "traefik.http.routers.zoneminder.tls.domains[0].main=zm3.f1961.nmac.com.ar"
