version: '3'
services:
  homeassistant:
    # container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      - ./config:/config
    restart: always
    ports:
      - 8124:8123
    depends_on:
      - mosquitto
    environment:
      - TZ=America/Montreal

  mosquitto:
    image: ansi/mosquitto
#    network_mode: host
    # container_name: homeassistant-mosquitto
    ports:
     - 1883:1883
    entrypoint: /usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
    volumes:
      - ./etc/mosquitto:/etc/mosquitto:ro
      - ./var/log/mosquitto:/var/log/mosquitto:rw
      - ./var/lib/mosquitto/mosquitto.db:/var/lib/mosquitto/mosquitto.db
    environment:
      - TZ=America/Montreal

  locative-endpoint:
    build: ../locative-endpoint
    container_name: locative-endpoint
    environment:
      - LOCATIVE_PORT=3998
    ports:
      - 3998:3998
    volumes:
      - ../locative-endpoint:/app
    command: /app/node_modules/nodemon/bin/nodemon.js /app/index.js

  ssl-nginx:
    image: nginx
    container_name: nginx-proxy
    ports:
      - 8443:443  # To serve HomeAssistant, SSL-Terminated (work in progress)
      - 8123:8123  # To serve HomeAssistant, SSL-Terminated (work in progress)
      - 3999:3999 # To serve locative endpoint
      - 4443:4443 # To serve locative endpoint, SSL (work in progress)
    volumes:
    - ./etc/nginx/locative.conf:/etc/nginx/conf.d/locative.conf
    - ./etc/nginx/homeassistant.conf:/etc/nginx/conf.d/homeassistant.conf
    - ./etc/certificates:/etc/certificates
    depends_on:
      - locative-endpoint
