version: '3'
services:
  homeassistant:
    image: homeassistant/home-assistant:0.90.1
    volumes:
      - ./config:/config
    restart: always
    ports:
      - 8124:8123
    depends_on:
      - mosquitto
    environment:
      - TZ=America/Montreal

  mosquitto:
    image: ansi/mosquitto
    ports:
     - 1883:1883
    entrypoint: /usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
    volumes:
      - ./etc/mosquitto:/etc/mosquitto:ro
      - ./var/log/mosquitto:/var/log/mosquitto:rw
      - ./var/lib/mosquitto/mosquitto.db:/var/lib/mosquitto/mosquitto.db
    environment:
      - TZ=America/Montreal

  locative-endpoint:
    build: ../locative-endpoint
    container_name: locative-endpoint
    environment:
      - LOCATIVE_PORT=3998
    ports:
      - 3998:3998
    volumes:
      - ../locative-endpoint:/app
    command: /app/node_modules/nodemon/bin/nodemon.js /app/index.js

  ssl-nginx:
    image: nginx
    ports:
      - 8123:8123 # To serve HomeAssistant plain text
      - 3999:3999 # To serve locative endpoint plain text
#      - 4443:4443 # To serve HomeAssistant and the cert, SSL (work in progress)
#      - 3997:3997 # To serve locative endpoint SSL
    volumes:
    - ./etc/nginx/locative.conf:/etc/nginx/conf.d/locative.conf
    - ./etc/nginx/homeassistant.conf:/etc/nginx/conf.d/homeassistant.conf
    - ./etc/certificates:/etc/certificates
    depends_on:
      - locative-endpoint
      - homeassistant

  tools-mqtt:
    image: node:8.15.0-alpine
    volumes:
    - ./tools:/code
    command: node /code/index.js
    