version: "3.4"
services:

  homeassistant:
    image: homeassistant/home-assistant:0.117.1
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config:/config
    depends_on:
      - mosquitto
      - locative-endpoint
    environment:
      - TZ=America/Montreal
    labels:
      - "traefik.frontend.rule=Host:1961fullum.nmac.com.ar"

  mosquitto:
    image: ansi/mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    entrypoint: /usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
    volumes:
      - ./etc/mosquitto:/etc/mosquitto:ro
      - ./var/log/mosquitto:/var/log/mosquitto:rw
      - ./var/lib/mosquitto/mosquitto.db:/var/lib/mosquitto/mosquitto.db:rw
    environment:
      - TZ=America/Montreal

  locative-endpoint:
    build: ../locative-endpoint
    container_name: locative-endpoint
    restart: unless-stopped
    environment:
      - LOCATIVE_PORT=3998
    ports:
      - 3998:3998
    volumes:
      - ../locative-endpoint:/app
#    command: /app/node_modules/nodemon/bin/nodemon.js /app/index.js

  ssl-nginx:
    image: nginx
    ports:
      - 4001:4001
#      - 3999:3999 # To serve locative endpoint plain text
    #      - 4443:4443 # To serve HomeAssistant and the cert, SSL (work in progress)
    #      - 3997:3997 # To serve locative endpoint SSL
    volumes:
 #     - ./etc/nginx/locative.conf:/etc/nginx/conf.d/locative.conf
#      - ./etc/nginx/homeassistant.conf:/etc/nginx/conf.d/homeassistant.conf
      - ./etc/nginx/wled.conf:/etc/nginx/conf.d/wled.conf
      - ./etc/certificates:/etc/certificates
    depends_on:
      - locative-endpoint
      - homeassistant



  cloud9: # https://hub.docker.com/r/sapk/cloud9/
    container_name: cloud9
    image: linuxserver/cloud9
    restart: unless-stopped
    privileged: true
    volumes:
    - ./:/code
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - PGID=1000
    # - PUID=99
    - TZ=America/Montreal
    - GITURL=https://github.com/linuxserver/docker-cloud9.git
    ports:
    - "8000:8000"
    labels:
    - "com.centurylinklabs.watchtower.enable=true"


  logs:
    image: gerchardon/docker-logio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -h logio -n docker
    depends_on:
      - logio
  logio:
    image: temal/logio-server
    ports:
      - 9002:28778
<<<<<<< HEAD

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    volumes:
    - ./volumes/duckdns/token/token:/config/token/token
    environment:
    - PUID=1000 #optional
    - PGID=1000 #optional
    - TZ=America/Montreal
    - SUBDOMAINS=micasanmaca
    - LOG_FILE=false
    - FILE__TOKEN=/config/token/token
    
=======
>>>>>>> c302279888bd268f7fb27e4e4df7d72ed876ad56
