- name: Alone - late
  entities:
    light.office_yee: off
    light.office_ceiling: off
    light.living_tortue: off
    light.living_moon:
      state: off
    light.office_ambient_light:
      state: on
      brightness: 20
      color_temp: 324
    light.office:
      state: on
      brightness: 60
    light.couch:
      state: on
      brightness: 50
    light.countertop:
      state: on
      brightness: 50
    light.kitchen:
      state: off

- name: Alone - evening
  entities:
    light.kitchen:
      state: on
      brightness: 132
    light.office:
      state: on
      brightness: 255
    light.couch:
      state: on
      brightness: 102
    light.countertop:
      state: on
      brightness: 102
    light.office_yee: off
    light.office_ceiling: off
    light.office_ambient_light:
      state: on
      brightness: 59
      color_temp: 358
    light.living_moon:
      state: off
    light.living_tortue:
        state: off

- name: Alarm
  entities:
    light.office_yee:
      state: on
      effect: "Police"
    light.countertop:
      state: on
      brightness: 255
    light.kitchen:
      state: on
      brightness: 255
    light.couch:
      state: on
      brightness: 255
    light.office:
      state: on
      brightness: 255
    light.living_moon:
      state: on
      effect: "Police"
    light.living_tortue:
      state: on
      effect: "Police"
