- name: Someone got home
  entities:
    light.moesdimmerliving:
      state: on
      brightness: 255
    light.moesdimmeroffice:
      state: on
      brightness: 128
    light.living_tortue:
      state: on
      brightness: 23
      color_temp: 360
  