
## Sends HA-desired values to the thermostat device through MQTT
- alias: ThermoDev 01
  trigger:
    - platform: state
      entity_id: input_number.office_temperature_slider
    - platform: time_pattern
      seconds: '/31'
      minutes: '/5'
  action:
    - service: mqtt.publish
      data_template:
        topic: '/ThermoDev/Desired01'
        retain: true
        payload: "{{ states('input_number.office_temperature_slider') | float }}"

## Sends HA-desired values to the thermostat device through MQTT
- alias: ThermoDev 02
  trigger:
    - platform: state
      entity_id: input_number.living_temperature_slider
    - platform: time_pattern
      seconds: '/31'
      minutes: '/5'
  action:
    service: mqtt.publish
    data_template:
      topic: '/ThermoDev/Desired02'
      retain: true
      payload: "{{ states('input_number.living_temperature_slider') | float }}"


- alias: Living Heater On
  trigger:
    platform: state
    entity_id: climate.living_climate
  condition:
    - condition: state
      entity_id: sensor.living_temperature_setpoint
      state: 'no'
  action:
    service: switch.turn_on
    entity_id: switch.living_heater
