- alias: Turn Exterior lights OFF at sunrise
  trigger:
  - platform: sun
    event: sunrise
    offset: "02:00:00"
  condition:
  action:
  - service: light.turn_off
    entity_id: group.lights_exterior

- alias: Turn Exterior lights ON at sunset
  trigger:
  - platform: sun
    event: sunset
    offset: "-02:00:00"
  condition:
  action:
  - service: light.turn_on
    entity_id: group.lights_exterior
    data:
      brightness: 190
      white_value: 255
      color_name: white
