alias: "Bathroom light at night OFF"
trigger:
- platform: state
  entity_id: sensor.movement_detected_near_bathroom
  to: 'off'
  from: 'on'
  for:
    seconds: 5
condition:
- condition: state
  entity_id: group.all_devices
  state: home
- condition: or  # 'when dark' condition: either after sunset or before sunrise
  conditions:
  - condition: time
    after: "18:00:00"
  - condition: time
    before: "8:00:00"
- condition: state
  entity_id: light.office
  state: 'on'
- condition: state
  entity_id: light.countertop
  state: 'on'
- condition: state
  entity_id: light.kitchen
  state: 'off'
- condition: state
  entity_id: light.bathroom
  state: 'off'
- condition: state
  entity_id: light.couch
  state: 'on'
- condition: numeric_state
  entity_id: light.office
  value_template: '{% if states.light.office.attributes.brightness == 1  %}1{% else %}0{% endif %}'
  above: 0
- condition: numeric_state
  entity_id: light.countertop
  value_template: '{% if states.light.countertop.attributes.brightness == 1  %}1{% else %}0{% endif %}'
  above: 0
- condition: numeric_state
  entity_id: light.couch
  value_template: '{% if states.light.couch.attributes.brightness == 1  %}1{% else %}0{% endif %}'
  above: 0
action:
- service: light.turn_off
  entity_id: light.office
- service: light.turn_off
  entity_id: light.countertop
- service: light.turn_off
  entity_id: light.couch
