- alias: "BreakfastDimmer is turned off"
  trigger:
  - platform: mqtt
    topic: lightvirtualdimmer01/sensor/rotary/state
    payload: 0
  action:
  - service: light.turn_off
    entity_id: light.countertop

- alias: "BreakfastDimmer is turned 1"
  trigger:
  - platform: mqtt
    topic: lightvirtualdimmer01/sensor/rotary/state
    payload: 1
  action:
  - service: light.turn_off
    entity_id: light.countertop
    data_template:
      brightness: 1

- alias: "BreakfastDimmer is turned > 1"
  trigger:
  - platform: mqtt
    topic: lightvirtualdimmer01/sensor/rotary/state
  condition:
  - condition: template
    value_template: >
      {% if trigger.payload == 0 or trigger.payload == 1 %}
        false
      {% else %}
        true
      {% endif %}
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.countertop
      brightness: '{{ 2 * 16 * (trigger.payload | float - 1) | int }}'
