alias: heaters enable
trigger:
  - platform: state
    entity_id:  group.all_devices
    to: 'home'
  - platform: state
    entity_id: input_number.at_home_temperature_slider
condition:
  - condition: state
    entity_id: group.all_devices
    state: home
action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.living_temperature_slider
      value: '{{ states.input_number.at_home_temperature_slider.state | float }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.office_temperature_slider
      value: '{{ states.input_number.at_home_temperature_slider.state | float }}'
  - service: rest_command.let_nico_know
    data_template:
      text: "Heaters set. Temperature set to {{ states.input_number.at_home_temperature_slider.state | float }}"
