alias: heaters disable
trigger:
  - platform: state
    entity_id: input_number.home_alone_temperature_slider
  - platform: state
    entity_id: group.all_devices
    to: 'not_home'
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: group.all_devices
    state: not_home
action:
  - service: mqtt.publish
    data_template:
      topic: '/HAYALGUIENONO'
      retain: true
      payload: "No hay nadiess"
  - service: input_number.set_value
    data_template:
      entity_id: input_number.living_temperature_slider
      value: '{{ states.input_number.home_alone_temperature_slider.state | float }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.office_temperature_slider
      value: '{{ states.input_number.home_alone_temperature_slider.state | float }}'
  - service: rest_command.let_nico_know
    data_template:
      text: "Home is alone. Temperature set to {{ states.input_number.home_alone_temperature_slider.state | float }}"
