alias: Exterior lights on at sunset
trigger:
- platform: sun
  event: sunset
condition:
action:
- service: light.turn_on
  entity_id: group.lights_exterior
  data:
    brightness: 190
    white_value: 255
    color_name: white

  