alias: Exterior lights on at sunset
trigger:
- platform: sun
  event: sunset
  offset: "-02:00:00"

condition:
 - condition: or  # 'when dark' condition: either after sunset or before sunrise - equivalent to a state condition on `sun.sun` of `below_horizon`
   conditions:
   - condition: sun
     after: sunset
   - condition: sun
     before: sunrise
action:
- service: light.turn_on
  entity_id: group.lights_exterior
  data:
    brightness: 255
    white_value: 255
    color_name: white

  