alias: Disable heaters while people sleeps
trigger:
  platform: state
  entity_id:  group.all_lights
  to: 'off'
condition:
  - condition: state
    entity_id: group.all_lights
    state: "off"
  - condition: time
    after: "00:10:00"
  - condition: time
    before: "07:00:00"
  - condition: state
    entity_id: group.all_devices
    state: home
action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.living_temperature_slider
      value: '{{ states.input_number.at_home_sleeping.state | float }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.living_temperature_slider
      value: '{{ states.input_number.at_home_sleeping.state | float }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.office_temperature_slider
      value: '{{ states.input_number.at_home_sleeping.state | float }}'
