alias: Lights on when someone arrives
trigger:
    - platform: state
      entity_id: group.all_devices
      to: home
condition:
  - condition: or  # 'when dark' condition: either after sunset or before sunrise
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-01:45:00"
      - condition: sun
        before: sunrise
action:
  - service: scene.turn_on
    entity_id: scene.someone_got_home
  - service: input_text.set_value
    data:
      entity_id: input_text.current_scene
      value: "Lights on when someone arrives"
