alias: Lights on when home is alone
trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
condition:
  condition: state
  entity_id: group.all_devices
  state: not_home
action:
  service: scene.turn_on
  entity_id: scene.home_alone__evening
