alias: Lights off when it is late
trigger:
    platform: time
    at: "01:00"
condition:
    - condition: state
      entity_id: group.all_devices
      state: not_home
action:
  service: homeassistant.turn_off
  entity_id: group.lights_interior
