alias: Lights on when home is alone
trigger:
- platform: sun
  event: sunset
  offset: "-01:00:00"
- platform: state
  entity_id: group.all_devices
  to: not_home
condition:
- condition: state
  entity_id: group.all_devices
  state: not_home
- condition: or  # 'when dark' condition: either after sunset or before sunrise
  conditions:
  - condition: time
    before: "01:00:00"
  - condition: sun
    after: sunset
    after_offset: "-02:10:00"
action:
- service: scene.turn_on
  entity_id: scene.alone_evening
- service: rest_command.let_nico_know
  data_template:
    text: "Turned lights on as per rule Lights on when home is alone"
