alias: Lights on when home is alone
trigger:
    - platform: sun
      event: sunset
    - platform: state
      entity_id: group.all_devices
      to: not_home
condition:
  - condition: state
    entity_id: group.all_devices
    state: not_home
  - condition:
    condition: or  # 'when dark' condition: either after sunset or before sunrise
    conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
action:
  service: scene.turn_on
  entity_id: scene.alone__evening
