- alias: Lights off when home is alone during daytime
  trigger:
  - platform: state
    entity_id: group.all_devices
    to: not_home
  - platform: sun
    event: sunrise
  condition:
  - condition: sun
    after: sunrise
    after_offset: "01:00:00"
  - condition: state
    entity_id: group.all_devices
    state: not_home
  - condition: sun
    before: sunset
    before_offset: "-01:00:00"
  action:
  - service: homeassistant.turn_off
    entity_id: group.lights_interior
- alias: Lights off when it is late
  trigger:
  - platform: time
    at: "01:01"
  - platform: state
    entity_id: group.all_devices
    to: not_home
  condition:
  - condition: state
    entity_id: group.all_devices
    state: not_home
  - condition: time
    after: "01:00"
  - condition: sun
    before: sunrise
  action:
  - service: light.turn_off
    entity_id: group.lights_interior
  - service: rest_command.let_nico_know
    data_template:
      text: "Turned lights off as per rule Lights off when it is late"


- alias: Lights on when someone arrives
  trigger:
    - platform: state
      entity_id: group.all_devices
      to: home
  condition:
    - condition: or  # 'when dark' condition: either after sunset or before sunrise
      conditions:
        - condition: sun
          after: sunset
          after_offset: "-01:45:00"
        - condition: sun
          before: sunrise
  action:
    - service: scene.turn_on
      entity_id: scene.someone_got_home
    - service: rest_command.let_nico_know
      data_template:
        text: "Lights on when someone arrives Kicked in: {{ states('group.all_devices') }}"

- alias: Lights on when home is alone
  trigger:
  - platform: sun
    event: sunset
    offset: "-02:00:00"
  - platform: state
    entity_id: group.all_devices
    to: not_home
  condition:
  - condition: state
    entity_id: group.all_devices
    state: not_home
  - condition: or  # 'when dark' condition: either after sunset or before sunrise
    conditions:
    - condition: time
      before: "01:00:00"
    - condition: sun
      after: sunset
      after_offset: "-02:10:00"
  action:
  - service: scene.turn_on
    entity_id: scene.alone_evening
  - service: rest_command.let_nico_know
    data_template:
      text: "Turned lights on as per rule Lights on when home is alone"
