alias: Lights off when home is alone during daytime
trigger:
- platform: state
  entity_id: group.all_devices
  to: not_home
- platform: sun
  event: sunrise
condition:
- condition: sun
  after: sunrise
  after_offset: "01:00:00"
- condition: state
  entity_id: group.all_devices
  state: not_home
- condition: sun
  before: sunset
  before_offset: "-01:00:00"
action:
- service: homeassistant.turn_off
  entity_id: group.lights_interior