- alias: Moes Dimmer Living Off
  trigger:
    - platform: state
      entity_id: light.livingdimmer
      from: "on"
      to: "off"
  condition:
  action:
    - service: light.turn_off
      entity_id: light.living_tortue

- alias: Moes Dimmer Living On
  trigger:
    - platform: state
      entity_id: light.livingdimmer
      to: "on"
  condition:
  action:
    - service: light.turn_on
      data_template:
        entity_id: group.living_tortue
        brightness: "{{ state_attr('light.livingdimmer', 'brightness')|int }}"
  # # {{states.light.moesdimmer01.attributes.brightness }}

