alias: Office Heater
trigger:
  platform: state
  entity_id: input_number.office_temperature
action:
  service: mqtt.publish
  data_template:
    topic: '/ThermoDev/Desired02'
    retain: true
    payload: "{{ states('input_number.office_temperature') | float }}"
