alias: Living Heater On
trigger:
  platform: state
  entity_id: sensor.living_temperature_setpoint
condition:
  - condition: state
    entity_id: sensor.living_temperature_setpoint
    state: 'yes'
action:
  service: switch.turn_off
  entity_id: switch.living_heater
