alias: ThermoDev 01
trigger:
  platform: state
  entity_id: input_number.living_temperature_slider
action:
  service: mqtt.publish
  data_template:
    topic: '/ThermoDev/Desired01'
    retain: true
    payload: "{{ states('input_number.living_temperature_slider') | float }}"
