alias: ThermoDev 02
trigger:
  - platform: state
    entity_id: input_number.living_temperature_slider
  - platform: time_pattern
    seconds: '/31'
    minutes: '/5'
action:
  service: mqtt.publish
  data_template:
    topic: '/ThermoDev/Desired02'
    retain: true
    payload: "{{ states('input_number.living_temperature_slider') | float }}"
