alias: ThermoDev 01
trigger:
  - platform: state
    entity_id: input_number.office_temperature_slider
  - platform: time
    seconds: '/31'
    minutes: '/2'
action:
  - service: mqtt.publish
    data_template:
      topic: '/ThermoDev/Desired01'
      retain: true
      payload: "{{ states('input_number.office_temperature_slider') | float }}"
