alias: Living Heater
trigger:
  platform: state
  entity_id: input_number.living_temperature
action:
  service: mqtt.publish
  data_template:
    topic: '/ThermoDev/Desired01'
    retain: true
    payload: "{{ states('input_number.living_temperature') | float }}"
