alias: ThermoDev 01
trigger:
  - platform: state
    entity_id: input_number.office_temperature_slider
  - platform: time
    minutes: '/5'
action:
  service: mqtt.publish
  data_template:
    topic: '/ThermoDev/Desired01'
    retain: true
    payload: "{{ states('input_number.office_temperature_slider') | float }}"
