alias: Living Heater On
trigger:
  platform: state
  entity_id: climate.living_climate
condition:
  - condition: state
    entity_id: sensor.living_temperature_setpoint
    state: 'no'
action:
  service: switch.turn_on
  entity_id: switch.living_heater
