alias: Moes Dimmer 01 ON
trigger:
- platform: state
  entity_id: light.moesdimmer_strips
  to: 'on'
- platform: mqtt
  topic: stat/sonoff/switch/living/RESULT/filtered
action:
- service: light.turn_on
  data_template:
    entity_id: group.lights_moesdimmer_strips
    brightness: "{{ state_attr('light.moesdimmer_strips', 'brightness')|int }}"

# {{states.light.moesdimmer01.attributes.brightness }} 