alias: Moes Dimmer 01 OFF
trigger:
- platform: state
  entity_id: light.moesdimmer01
  from: 'on'
  to: 'off'
condition:
action:
- service: light.turn_off
  entity_id: group.lights_moesdimmer01
# {{states.light.moesdimmer01.attributes.brightness }} 