alias: Moes Dimmer 02 OFF
trigger:
- platform: state
  entity_id: light.moesdimmer02
  from: 'on'
  to: 'off'
condition:
action:
- service: light.turn_off
  entity_id: group.lights_moesdimmer02
- service: light.turn_off
  entity_id: light.office_yee
- service: light.turn_off
  entity_id: light.office_yee  
# {{states.light.moesdimmer01.attributes.brightness }} 