alias: Moes Dimmer 01 ON
trigger:
# - platform: state
#   entity_id: light.moesdimmer01
#   to: 'on'
- platform: mqtt
  topic: stat/sonoff/switch/living/RESULT
action:
- service: light.turn_on
  data_template:
    entity_id: group.lights_moesdimmer01
    brightness: "{{ state_attr('light.moesdimmer01', 'brightness')|int }}"

# {{states.light.moesdimmer01.attributes.brightness }} 