alias: Moes Dimmer 02 ON
trigger:
- platform: state
  entity_id: light.moesdimmer02
  to: 'on'
- platform: mqtt
  topic: stat/sonoff/switch/office/RESULT
action:
- service: light.turn_on
  data_template:
    entity_id: group.lights_moesdimmer02
    brightness: "{{  state_attr('light.moesdimmer02', 'brightness')|int }}"

# {{states.light.moesdimmer01.attributes.brightness }} 