alias: Moes Dimmer Dev OFF
trigger:
- platform: state
  entity_id: light.moesdimmerdev
  from: 'on'
  to: 'off'
condition:
action:
- service: light.turn_off
  entity_id: group.lights_moesdimmerdev
# {{states.light.moesdimmer01.attributes.brightness }} 