alias: Notify presence changes
trigger:
  - platform: state
    entity_id: group.all_devices
    to: 'not_home'
  - platform: state
    entity_id: group.all_devices
    to: 'home'
action:
  - service: rest_command.let_nico_know
    data_template:
      text: "Presence change. Presence set to: {{ states('group.all_devices') }}"
