alias: Screen Listener ButtonUp
trigger:
  - platform: mqtt
    topic: /Screen01/Climate/DesiredTemperatureButton
    payload: '++'
action:
  - service: mqtt.publish
    data_template:
      topic: '/Home/Climate/DesiredTemperature'
      retain: true
      payload: '{{ (states.input_number.at_home_temperature_slider.state | float) + 0.5 }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.at_home_temperature_slider
      value: '{{ (states.input_number.at_home_temperature_slider.state | float) + 0.5 }}'
