alias: Screen01 Listener Global OnOff
trigger:
  - platform: mqtt
    topic: /Screen01/Lights/Global/OnOff
    payload: 'OnOff'
action:
  - service: homeassistant.turn_off
    entity_id: group.all_lights
