- id: '1596239747422'
  alias: Turn ON Front Door
  description: ''
  trigger:
  - event: sunset
    platform: sun
    offset: '-1:00:00'
  condition: []
  action:
  - data:
      brightness: 255
    service: light.turn_on
    target:
      entity_id: light.front_door
  mode: single
- id: '1596240356692'
  alias: Turn OFF Front Door
  description: Turn OFF Front Door
  trigger:
  - event: sunrise
    offset: '+2'
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: light.front_door
    service: light.turn_off
  mode: single
- id: '1596240582832'
  alias: Sleep
  description: Sleep
  trigger:
  - device_id: b13d461c3f2b47feba54e6ee3f6157e7
    domain: hue
    platform: device
    subtype: turn_off
    type: remote_button_long_release
  - device_id: dad66e279b9244d3abaed6129a4b0161
    domain: hue
    platform: device
    subtype: turn_off
    type: remote_button_long_release
  - device_id: c0c4aa0522644d4e82aafd9794d4f957
    domain: hue
    platform: device
    subtype: button_4
    type: remote_button_short_press
  condition: []
  action:
  - data: {}
    entity_id: group.lights_interior
    service: light.turn_off
  mode: single
- id: '1597004549461'
  alias: Hue - Office dimmer - long-on when lamp on
  description: Turns on the lamps
  trigger:
  - device_id: b13d461c3f2b47feba54e6ee3f6157e7
    domain: hue
    platform: device
    subtype: turn_on
    type: remote_button_long_release
  condition:
  - condition: state
    entity_id: light.office_back_lamp
    state: 'on'
  action:
  - data: {}
    entity_id: light.office_back_lamp
    service: light.turn_off
  mode: single
- id: '1597004732813'
  alias: Office hue dimmer - long on when lamp off (turn it on)
  description: ''
  trigger:
  - device_id: b13d461c3f2b47feba54e6ee3f6157e7
    domain: hue
    platform: device
    subtype: turn_on
    type: remote_button_long_release
  condition:
  - condition: state
    entity_id: light.office_back_lamp
    state: 'off'
  action:
  - data:
      brightness: 255
      rgb_color:
      - 255
      - 0
      - 255
      transition: 2
    entity_id: light.office_back_lamp
    service: light.turn_on
  mode: single
- id: '1598587050856'
  alias: WLED 01 Adjustments
  description: ''
  trigger:
  - entity_id: input_number.wled01_speed
    platform: state
  - entity_id: input_number.wled01_intensity
    platform: state
  condition: []
  action:
  - data_template:
      intensity: '{{ states(''input_number.wled01_intensity'') | default(0, true)
        | int }}

        '
      speed: '{{ states(''input_number.wled01_speed'') | default(0, true) | int }}

        '
    entity_id: light.wledoffice
    service: wled.effect
  mode: single
- id: '1598751390007'
  alias: Living Dimmer - Living Moon
  description: ''
  trigger:
  - entity_id: light.livingdimmer
    platform: state
  condition: []
  action:
  - data_template:
      brightness: '{{ state_attr(''light.livingdimmer'', ''brightness'') | default(0,
        true) }}

        '
    entity_id: light.living_moon
    service: light.turn_on
  mode: single
- id: '1607490599558'
  alias: Temperature - Sleeping
  description: ''
  trigger:
  - platform: state
    entity_id: group.lights_interior
    to: 'off'
    from: 'on'
    for: 00:00:05
  - platform: time
    at: '22:00:30'
  condition:
  - condition: and
    conditions:
    - condition: or
      conditions:
      - condition: time
        before: 06:00
      - condition: time
        after: '22:00'
    - condition: state
      entity_id: group.lights_interior
      state: 'off'
      for: 00:00:05
  action:
  - service: input_number.set_value
    data:
      value: 18
    entity_id: input_number.main_room_temperature
  mode: single
- id: '1607609003902'
  alias: Temperature - WakeUp
  description: ''
  trigger:
  - platform: time
    at: '7:00'
  condition: []
  action:
  - service: input_number.set_value
    data:
      value: 20
    target:
      entity_id: input_number.main_room_temperature
  mode: single
- id: '1608174278630'
  alias: Main Room Temp
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.main_room_temperature
  condition: []
  action:
  - service: climate.set_temperature
    data_template:
      temperature: '{{ states(''input_number.main_room_temperature'') | float }}

        '
    target:
      entity_id:
      - climate.climate_kitchen
      - climate.climate_office
      - climate.climate_living
  mode: single
- id: '1608332036920'
  alias: Hue Tap Main Button
  description: ''
  trigger:
  - device_id: c0c4aa0522644d4e82aafd9794d4f957
    domain: hue
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.light_bedroom_candle_light
      brightness: "{% if states.light.light_bedroom_candle_light.state == \"off\"\
        \ %}\n2\n{% else %}\n  {% if (states.light.light_bedroom_candle_light.attributes.brightness\
        \ | int) < 80 %}\n84\n  {% elif (states.light.light_bedroom_candle_light.attributes.brightness\
        \ | int) < 165 %}\n168\n  {% elif (states.light.light_bedroom_candle_light.attributes.brightness\
        \ | int) < 250 %}\n254\n  {% elif (states.light.light_bedroom_candle_light.attributes.brightness\
        \ | int) > 240 %}\n  0\n  {% endif %}\n{% endif %}\n"
  mode: single
- id: '1611288873479'
  alias: Hue Tap 3rd Button
  description: ''
  trigger:
  - device_id: c0c4aa0522644d4e82aafd9794d4f957
    domain: hue
    platform: device
    type: remote_button_short_press
    subtype: button_3
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.space_lamp_light
      brightness: "{% if states.light.space_lamp_light.state == \"off\" %}\n255\n\
        {% else %}\n 0\n{% endif %}\n"
  mode: single
- id: '1615737828189'
  alias: Bedroom dimmer Nico
  description: ''
  trigger:
  - platform: state
    entity_id: light.bedroom_main_dimmer
  condition: []
  action:
  - data_template:
      brightness: '{{ state_attr(''light.bedroom_main_dimmer'', ''brightness'') |
        default(0, true) }}

        '
    entity_id: light.bedroom_main_lamp
    service: light.turn_on
  mode: single
- id: '1615739257841'
  alias: Dimmer Vick's spot
  description: ''
  trigger:
  - platform: state
    entity_id: light.vicks_spot_main_dimmer
  condition: []
  action:
  - data_template:
      brightness: '{{ state_attr(''light.vicks_spot_main_dimmer'', ''brightness'')
        | default(0, true) }}

        '
    entity_id: light.vicks_spot_main_lamp
    service: light.turn_on
  mode: single
- id: '1617365553303'
  alias: Disable IR Leds from cameras
  description: ''
  trigger:
  - platform: time_pattern
    hours: '*'
    minutes: /2
    seconds: '15'
  condition: []
  action:
  - service: rest_command.disable_camera_ir
    data: {}
  mode: single
- id: '1617550784376'
  alias: Remote Dimmer for Countertop - On and Dim
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 2513d915a926f8c96dbc42ea12f0aefb
    type: action
    subtype: on-press
    discovery_id: 0x0017880104f026ab action_on-press
  - platform: device
    domain: mqtt
    device_id: 2513d915a926f8c96dbc42ea12f0aefb
    type: action
    subtype: up-press
    discovery_id: 0x0017880104f026ab action_up-press
  - platform: device
    domain: mqtt
    device_id: 2513d915a926f8c96dbc42ea12f0aefb
    type: action
    subtype: on-hold
    discovery_id: 0x0017880104f026ab action_on-hold
  - platform: device
    domain: mqtt
    device_id: 2513d915a926f8c96dbc42ea12f0aefb
    type: action
    subtype: up-hold
    discovery_id: 0x0017880104f026ab action_up-hold
  condition: []
  action:
  - service: system_log.write
    data:
      message: '{{ trigger }}'
  - service: light.turn_on
    data:
      entity_id: "{%if trigger.payload == 'on-press' or trigger.payload == 'on-hold'%}\n\
        \  light.countertop\n{%elif trigger.payload == 'up-press' or trigger.payload\
        \ == 'up-hold' %}\n  light.kitchen_lamp\n{%endif%}\n"
      brightness: "{%if trigger.payload == 'on-hold' or trigger.payload == 'up-hold'\
        \ %}\n  255\n{%elif trigger.payload == 'on-press'%}\n  {% if states.light.countertop.state\
        \ == \"off\" or ((states.light.countertop.attributes.brightness | int) * (100\
        \ / 255)) < 20  or ((states.light.countertop.attributes.brightness | int)\
        \ * (100 / 255)) > 95 %}\n  {{ 255 * 25 / 100 | int }}\n  {% elif ((states.light.countertop.attributes.brightness\
        \ | int) * (100 / 255)) < 40 %}\n  {{ 255 * 50 / 100 | int }}\n  {% elif ((states.light.countertop.attributes.brightness\
        \ | int) * (100 / 255)) < 65 %}\n  {{ 255 * 75 / 100 | int }}\n  {% elif ((states.light.countertop.attributes.brightness\
        \ | int) * (100 / 255)) < 90 %}\n  {{ 255 * 100 / 100 | int }}\n  {% endif\
        \ %}\n{%elif trigger.payload == 'up-press' %}\n  {% if states.light.kitchen_lamp.state\
        \ == \"off\" or ((states.light.kitchen_lamp.attributes.brightness | int) *\
        \ (100 / 255)) < 20  or ((states.light.kitchen_lamp.attributes.brightness\
        \ | int) * (100 / 255)) > 95 %}\n  {{ 255 * 25 / 100 | int }}\n  {% elif ((states.light.kitchen_lamp.attributes.brightness\
        \ | int) * (100 / 255)) < 40 %}\n  {{ 255 * 50 / 100 | int }}\n  {% elif ((states.light.kitchen_lamp.attributes.brightness\
        \ | int) * (100 / 255)) < 65 %}\n  {{ 255 * 75 / 100 | int }}\n  {% elif ((states.light.kitchen_lamp.attributes.brightness\
        \ | int) * (100 / 255)) < 90 %}\n  {{ 255 * 100 / 100 | int }}\n  {% endif\
        \ %}\n{%endif%}\n"
  mode: single
- id: '1617553867970'
  alias: Remote Dimmer for Countertop - Off
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 2513d915a926f8c96dbc42ea12f0aefb
    type: action
    subtype: down-press
    discovery_id: 0x0017880104f026ab action_down-press
  - platform: device
    domain: mqtt
    device_id: 2513d915a926f8c96dbc42ea12f0aefb
    type: action
    subtype: off-press
    discovery_id: 0x0017880104f026ab action_off-press
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: "{%if trigger.payload == 'off-press' %}\n  light.countertop\n{%elif\
        \ trigger.payload == 'down-press'%}\n  light.kitchen_lamp\n{%endif%}\n"
  mode: single
- id: '1621693900634'
  alias: Kitchen Magic Cube
  description: ''
  use_blueprint:
    path: luckypoppy/z2m-xiaomi-cube-controller.yaml
    input:
      slide_face_0: []
      flipped180_face_0:
      - service: light.toggle
        data: {}
        entity_id: light.countertop
      - service: light.toggle
        data: {}
        entity_id: light.kitchen_lamp
      flipped180_face_1:
      - service: light.toggle
        data: {}
        entity_id: light.countertop
      - service: light.toggle
        data: {}
        entity_id: light.kitchen_lamp
      flipped180_face_2:
      - service: light.toggle
        data: {}
        entity_id: light.countertop
      - service: light.toggle
        data: {}
        entity_id: light.kitchen_lamp
      flipped180_face_3:
      - service: light.toggle
        data: {}
        entity_id: light.countertop
      - service: light.toggle
        data: {}
        entity_id: light.kitchen_lamp
      flipped180_face_4:
      - service: light.toggle
        data: {}
        entity_id: light.countertop
      - service: light.toggle
        data: {}
        entity_id: light.kitchen_lamp
      flipped180_face_5:
      - service: light.toggle
        data: {}
        entity_id: light.countertop
      - service: light.toggle
        data: {}
        entity_id: light.kitchen_lamp
      remote: sensor.0x00158d000544a42e_action
- id: '1621696669089'
  alias: Kitchen Cube Lamp - Flip 180
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt-aqara/aqara-cube-kitchen
    payload: flip180
    value_template: '{{ value_json.action }}'
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.kitchen_lamp
  mode: single
- id: '1621715079279'
  alias: Office Cube - Slides
  description: ''
  trigger:
  - platform: mqtt
    payload: slide
    value_template: '{{ value_json.action }}'
    topic: zigbee2mqtt-aqara/aqara-cube-office
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.office_yee
  - service: light.toggle
    data: {}
    target:
      entity_id: light.office_right
  mode: single
- id: '1621805678074'
  alias: Kitchen Cube Shake
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt-aqara/aqara-cube-kitchen
    payload: shake
    value_template: '{{ value_json.action }}'
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.countertop
  mode: single
- id: '1623463299404'
  alias: Home Alone - Turn On lights
  description: ''
  trigger:
  - platform: time
    at: '18:00'
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
    target:
      entity_id:
      - light.countertop
      - light.kitchen_lamp
      - light.bedroom_main_lamp
      - light.light_bedroom_candle
      - light.office_yee
      - light.office_right
  mode: single
- id: '1623463348926'
  alias: Home Alone - Turn Off lights
  description: ''
  trigger:
  - platform: time
    at: 00:30
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id:
      - light.countertop
      - light.kitchen_lamp
      - light.bedroom_main_lamp
      - light.light_bedroom_candle
      - light.office_yee
      - light.office_right
  mode: single
- id: '1629250564408'
  alias: WLedOffice White Set
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.wledoffice_kelvin
  condition: []
  action:
  - service: light.turn_on
    data_template:
      kelvin: '{{ states(''input_number.wledoffice_kelvin'') | int(1) }}'
    target:
      device_id: 3aafe1d34f701960fe66d2c2da0b05b8
  mode: single
- id: '1629415038976'
  alias: Cube - Living
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt-aqara/aqara-cube-living
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''action_angle''] is defined and trigger.payload_json[''action'']
      is defined and trigger.payload_json[''action''].startswith(''rotate_'') }}'
  action:
  - service: light.turn_on
    target:
      entity_id: light.living_tortue
    data_template:
      brightness: '{{ [[0, 0.2*(trigger.payload_json[''action_angle'']|int) + state_attr(''light.living_tortue'',
        ''brightness'')|int ] | max, 255] | min}}'
  mode: single
- id: '1635615687363'
  alias: Hue Tap Main button
  description: ''
  trigger:
  - device_id: 6c956e0be86aaba5d02340450928c65b
    domain: hue
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition: []
  action:
  - type: toggle
    device_id: e936f07a56b52552a8646d57e13c2731
    entity_id: light.light_bedroom_candle
    domain: light
  mode: single
