- id: '1596239747422'
  alias: Turn ON Front Door
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      brightness: 255
    entity_id: light.front_door
    service: light.turn_on
  mode: single
- id: '1596240356692'
  alias: Turn OFF Front Door
  description: Turn OFF Front Door
  trigger:
  - event: sunrise
    offset: '+2'
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: light.front_door
    service: light.turn_off
  mode: single
- id: '1596240582832'
  alias: Sleep
  description: Sleep
  trigger:
  - device_id: b13d461c3f2b47feba54e6ee3f6157e7
    domain: hue
    platform: device
    subtype: turn_off
    type: remote_button_long_release
  - device_id: dad66e279b9244d3abaed6129a4b0161
    domain: hue
    platform: device
    subtype: turn_off
    type: remote_button_long_release
  - device_id: c0c4aa0522644d4e82aafd9794d4f957
    domain: hue
    platform: device
    subtype: button_4
    type: remote_button_short_press
  condition: []
  action:
  - data: {}
    entity_id: group.lights_interior
    service: light.turn_off
  mode: single
- id: '1596487473709'
  alias: Dimmer 05
  description: ''
  trigger:
  - entity_id: light.dimmer05
    platform: state
  condition: []
  action:
  - data_template:
      brightness: '{{ state_attr(''light.dimmer05'', ''brightness'') | default(0,
        true) }}

        '
    entity_id: light.yeelight_color_0x0000000007e7228c
    service: light.turn_on
  mode: single
- id: '1597004549461'
  alias: Hue - Office dimmer - long-on when lamp on
  description: Turns on the lamps
  trigger:
  - device_id: b13d461c3f2b47feba54e6ee3f6157e7
    domain: hue
    platform: device
    subtype: turn_on
    type: remote_button_long_release
  condition:
  - condition: state
    entity_id: light.office_back_lamp
    state: 'on'
  action:
  - data: {}
    entity_id: light.office_back_lamp
    service: light.turn_off
  mode: single
- id: '1597004732813'
  alias: Office hue dimmer - long on when lamp off (turn it on)
  description: ''
  trigger:
  - device_id: b13d461c3f2b47feba54e6ee3f6157e7
    domain: hue
    platform: device
    subtype: turn_on
    type: remote_button_long_release
  condition:
  - condition: state
    entity_id: light.office_back_lamp
    state: 'off'
  action:
  - data:
      brightness: 255
      rgb_color:
      - 255
      - 0
      - 255
      transition: 2
    entity_id: light.office_back_lamp
    service: light.turn_on
  mode: single
- id: '1598587050856'
  alias: WLED 01 Adjustments
  description: ''
  trigger:
  - entity_id: input_number.wled01_speed
    platform: state
  - entity_id: input_number.wled01_intensity
    platform: state
  condition: []
  action:
  - data_template:
      intensity: '{{ states(''input_number.wled01_intensity'') | default(0, true)
        | int }}

        '
      speed: '{{ states(''input_number.wled01_speed'') | default(0, true) | int }}

        '
    entity_id: light.wled
    service: wled.effect
  mode: single
- id: '1598751390007'
  alias: Living Dimmer - Living Moon
  description: ''
  trigger:
  - entity_id: light.livingdimmer
    platform: state
  condition: []
  action:
  - data_template:
      brightness: '{{ state_attr(''light.livingdimmer'', ''brightness'') | default(0,
        true) }}

        '
    entity_id: light.living_moon
    service: light.turn_on
  mode: single
- id: '1602286184225'
  alias: ThermoDev Heater Living .220
  description: ''
  trigger:
  - entity_id: input_number.living_temperature_slider
    platform: state
  condition: []
  action:
  - data:
      payload_template: '{{ states(''input_number.living_temperature_slider'') }}

        '
      topic: /ThermoDev/Desired02
    service: mqtt.publish
  mode: single
- id: '1602286338110'
  alias: ThermoDev Heater Office .220
  description: ''
  trigger:
  - entity_id: input_number.office_temperature_slider
    platform: state
  condition: []
  action:
  - data:
      payload_template: '{{ states(''input_number.office_temperature_slider'') }}

        '
      topic: /ThermoDev/Desired01
    service: mqtt.publish
  mode: single
- id: '1607490599558'
  alias: Temperature - Sleeping
  description: ''
  trigger:
  - platform: state
    entity_id: group.lights_interior
    to: 'off'
  - platform: time
    at: '23:10'
  condition:
  - condition: or
    conditions:
    - condition: time
      after: '23:00'
    - condition: time
      before: '4:00'
  - condition: state
    entity_id: group.lights_interior
    state: 'off'
  action:
  - service: climate.set_temperature
    data:
      temperature: 17.5
      entity_id:
      - climate.0xf8f005fffff781ab_climate
      - climate.0xf8f005fffff483ab_climate
  - service: input_number.set_value
    data:
      value: 17.5
      entity_id:
      - input_number.office_temperature_slider
      - input_number.living_temperature_slider
  mode: single
- id: '1607609003902'
  alias: Temperature - WakeUp
  description: ''
  trigger:
  - platform: time
    at: '7:00'
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 20.5
      entity_id:
      - climate.0xf8f005fffff781ab_climate
      - climate.0xf8f005fffff483ab_climate
  - service: input_number.set_value
    data:
      value: 20.5
      entity_id:
      - input_number.office_temperature_slider
      - input_number.living_temperature_slider
  mode: single
- id: '1608174278630'
  alias: Main Room Temp
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.main_room_temperature
  condition: []
  action:
  - service: input_number.set_value
    data:
      value: '{{ states.input_number.main_room_temperature.state | float }}

        '
      entity_id:
      - input_number.office_temperature_slider
      - input_number.living_temperature_slider
  - service: climate.set_temperature
    data:
      entity_id: climate.0xf8f005fffff781ab_climate
      temperature: '{{ states.input_number.main_room_temperature.state | float }}

        '
  mode: single
