- id: '1596239747422'
  alias: Turn ON Front Door
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      brightness: 255
    entity_id: light.front_door
    service: light.turn_on
  mode: single
- id: '1596240356692'
  alias: Turn OFF Front Door
  description: Turn OFF Front Door
  trigger:
  - event: sunrise
    offset: '+2'
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: light.front_door
    service: light.turn_off
  mode: single
- id: '1596240582832'
  alias: Sleep
  description: Sleep
  trigger:
  - device_id: b13d461c3f2b47feba54e6ee3f6157e7
    domain: hue
    platform: device
    subtype: turn_off
    type: remote_button_long_release
  - device_id: dad66e279b9244d3abaed6129a4b0161
    domain: hue
    platform: device
    subtype: turn_off
    type: remote_button_long_release
  - device_id: c0c4aa0522644d4e82aafd9794d4f957
    domain: hue
    platform: device
    subtype: button_4
    type: remote_button_short_press
  condition: []
  action:
  - data: {}
    entity_id: group.lights_interior
    service: light.turn_off
  mode: single
- id: '1596487473709'
  alias: Dimmer 05
  description: ''
  trigger:
  - entity_id: light.dimmer05
    platform: state
  condition: []
  action:
  - data_template:
      brightness: '{{ state_attr(''light.dimmer05'', ''brightness'') | default(0,
        true) }}

        '
    entity_id: light.downlight_01_downlight_01
    service: light.turn_on
  mode: single
- id: '1597004549461'
  alias: Hue - Office dimmer - long-on when lamp on
  description: Turns on the lamps
  trigger:
  - device_id: b13d461c3f2b47feba54e6ee3f6157e7
    domain: hue
    platform: device
    subtype: turn_on
    type: remote_button_long_release
  condition:
  - condition: state
    entity_id: light.office_ambient_lamp
    state: 'on'
  action:
  - data: {}
    entity_id: light.office_ambient_lamp
    service: light.turn_off
  mode: single
- id: '1597004732813'
  alias: Office hue dimmer - long on when lamp off (turn it on)
  description: ''
  trigger:
  - device_id: b13d461c3f2b47feba54e6ee3f6157e7
    domain: hue
    platform: device
    subtype: turn_on
    type: remote_button_long_release
  condition:
  - condition: state
    entity_id: light.office_ambient_lamp
    state: 'off'
  action:
  - data:
      brightness: 255
      rgb_color:
      - 255
      - 0
      - 255
      transition: 2
    entity_id: light.office_ambient_lamp
    service: light.turn_on
  mode: single
