- id: '1596239747422'
  alias: Turn ON Front Door
  description: ''
  trigger:
  - event: sunset
    platform: sun
    offset: '-1:00:00'
  condition: []
  action:
  - data:
      brightness: 255
    service: light.turn_on
    target:
      device_id: aaf4f8bd5c2ad491de2ea504671d8c2e
  mode: single
- id: '1596240356692'
  alias: Turn OFF Front Door
  description: Turn OFF Front Door
  trigger:
  - event: sunrise
    offset: '+2'
    platform: sun
  condition: []
  action:
  - data: {}
    service: light.turn_off
    target:
      device_id: aaf4f8bd5c2ad491de2ea504671d8c2e
  mode: single
- id: '1596240582832'
  alias: Sleep
  description: Sleep
  trigger:
  - device_id: b13d461c3f2b47feba54e6ee3f6157e7
    domain: hue
    platform: device
    subtype: turn_off
    type: remote_button_long_release
  - device_id: dad66e279b9244d3abaed6129a4b0161
    domain: hue
    platform: device
    subtype: turn_off
    type: remote_button_long_release
  - device_id: c0c4aa0522644d4e82aafd9794d4f957
    domain: hue
    platform: device
    subtype: button_4
    type: remote_button_short_press
  condition: []
  action:
  - data: {}
    entity_id: group.lights_interior
    service: light.turn_off
  mode: single
- id: '1597004549461'
  alias: Hue - Office dimmer - long-on when lamp on
  description: Turns on the lamps
  trigger:
  - device_id: b13d461c3f2b47feba54e6ee3f6157e7
    domain: hue
    platform: device
    subtype: turn_on
    type: remote_button_long_release
  condition:
  - condition: state
    entity_id: light.office_back_lamp
    state: 'on'
  action:
  - data: {}
    entity_id: light.office_back_lamp
    service: light.turn_off
  mode: single
- id: '1597004732813'
  alias: Office hue dimmer - long on when lamp off (turn it on)
  description: ''
  trigger:
  - device_id: b13d461c3f2b47feba54e6ee3f6157e7
    domain: hue
    platform: device
    subtype: turn_on
    type: remote_button_long_release
  condition:
  - condition: state
    entity_id: light.office_back_lamp
    state: 'off'
  action:
  - data:
      brightness: 255
      rgb_color:
      - 255
      - 0
      - 255
      transition: 2
    entity_id: light.office_back_lamp
    service: light.turn_on
  mode: single
- id: '1598587050856'
  alias: WLED 01 Adjustments
  description: ''
  trigger:
  - entity_id: input_number.wled01_speed
    platform: state
  - entity_id: input_number.wled01_intensity
    platform: state
  condition: []
  action:
  - data_template:
      intensity: '{{ states(''input_number.wled01_intensity'') | default(0, true)
        | int }}

        '
      speed: '{{ states(''input_number.wled01_speed'') | default(0, true) | int }}

        '
    entity_id: light.wledoffice
    service: wled.effect
  mode: single
- id: '1607490599558'
  alias: Temperature - Sleeping
  description: ''
  trigger:
  - platform: state
    entity_id: group.lights_interior
    to: 'off'
    from: 'on'
    for: 00:00:05
  - platform: time
    at: '22:00'
  condition:
  - condition: and
    conditions:
    - condition: or
      conditions:
      - condition: time
        before: 06:00
      - condition: time
        after: '20:00'
    - condition: state
      entity_id: group.lights_interior
      state: 'off'
      for: 00:00:05
  action:
  - service: input_number.set_value
    data:
      value: 17.5
    target:
      entity_id: input_number.main_room_temperature
  mode: single
- id: '1607609003902'
  alias: Temperature - WakeUp
  description: ''
  trigger:
  - platform: time
    at: 06:30:00
  - platform: state
    entity_id: binary_sensor.is_someone_at_home
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  condition:
  - condition: state
    entity_id: binary_sensor.is_someone_at_home
    state: 'on'
  action:
  - service: input_number.set_value
    data:
      value: 21
    target:
      entity_id: input_number.main_room_temperature
  mode: single
- id: '1608174278630'
  alias: Main Room Temp
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.main_room_temperature
  condition: []
  action:
  - service: climate.set_temperature
    data_template:
      temperature: '{{ states(''input_number.main_room_temperature'') | float }}

        '
    target:
      entity_id:
      - climate.climate_kitchen
      - climate.climate_living
  - service: climate.set_temperature
    data_template:
      temperature: '{{ states(''input_number.main_room_temperature'') | float + 0.5}}

        '
    target:
      entity_id:
      - climate.climate_office
  mode: single
- id: '1608332036920'
  alias: Hue Tap Main Button
  description: ''
  trigger:
  - device_id: c0c4aa0522644d4e82aafd9794d4f957
    domain: hue
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.light_bedroom_candle_light
      brightness: "{% if states.light.light_bedroom_candle_light.state == \"off\"\
        \ %}\n2\n{% else %}\n  {% if (states.light.light_bedroom_candle_light.attributes.brightness\
        \ | int) < 80 %}\n84\n  {% elif (states.light.light_bedroom_candle_light.attributes.brightness\
        \ | int) < 165 %}\n168\n  {% elif (states.light.light_bedroom_candle_light.attributes.brightness\
        \ | int) < 250 %}\n254\n  {% elif (states.light.light_bedroom_candle_light.attributes.brightness\
        \ | int) > 240 %}\n  0\n  {% endif %}\n{% endif %}\n"
  mode: single
- id: '1611288873479'
  alias: Hue Tap 3rd Button
  description: ''
  trigger:
  - device_id: c0c4aa0522644d4e82aafd9794d4f957
    domain: hue
    platform: device
    type: remote_button_short_press
    subtype: button_3
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.space_lamp_light
      brightness: "{% if states.light.space_lamp_light.state == \"off\" %}\n255\n\
        {% else %}\n 0\n{% endif %}\n"
  mode: single
- id: '1615737828189'
  alias: Bedroom dimmer Nico
  description: ''
  trigger:
  - platform: state
    entity_id: light.bedroom_main_dimmer
  condition: []
  action:
  - data_template:
      brightness: '{{ state_attr(''light.bedroom_main_dimmer'', ''brightness'') |
        default(0, true) }}

        '
    entity_id: light.bedroom_main_lamp
    service: light.turn_on
  mode: single
- id: '1615739257841'
  alias: Dimmer Vick's spot
  description: ''
  trigger:
  - platform: state
    entity_id: light.vicks_spot_main_dimmer
  condition: []
  action:
  - data_template:
      brightness: '{{ state_attr(''light.vicks_spot_main_dimmer'', ''brightness'')
        | default(0, true) }}

        '
    entity_id: light.vicks_spot_main_lamp
    service: light.turn_on
  mode: single
- id: '1621693900634'
  alias: Kitchen Magic Cube
  description: ''
  use_blueprint:
    path: luckypoppy/z2m-xiaomi-cube-controller.yaml
    input:
      slide_face_0: []
      flipped180_face_0:
      - service: light.toggle
        data: {}
        entity_id: light.countertop
      - service: light.toggle
        data: {}
        entity_id: light.kitchen_lamp
      flipped180_face_1:
      - service: light.toggle
        data: {}
        entity_id: light.countertop
      - service: light.toggle
        data: {}
        entity_id: light.kitchen_lamp
      flipped180_face_2:
      - service: light.toggle
        data: {}
        entity_id: light.countertop
      - service: light.toggle
        data: {}
        entity_id: light.kitchen_lamp
      flipped180_face_3:
      - service: light.toggle
        data: {}
        entity_id: light.countertop
      - service: light.toggle
        data: {}
        entity_id: light.kitchen_lamp
      flipped180_face_4:
      - service: light.toggle
        data: {}
        entity_id: light.countertop
      - service: light.toggle
        data: {}
        entity_id: light.kitchen_lamp
      flipped180_face_5:
      - service: light.toggle
        data: {}
        entity_id: light.countertop
      - service: light.toggle
        data: {}
        entity_id: light.kitchen_lamp
      remote: sensor.0x00158d000544a42e_action
- id: '1621696669089'
  alias: Kitchen Cube Lamp - Flip 180
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt-aqara/aqara-cube-kitchen
    payload: flip180
    value_template: '{{ value_json.action }}'
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.kitchen_lamp
  mode: single
- id: '1621715079279'
  alias: Office Cube - Slides
  description: ''
  trigger:
  - platform: mqtt
    payload: slide
    value_template: '{{ value_json.action }}'
    topic: zigbee2mqtt-aqara/aqara-cube-office
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.office_yee
  - service: light.toggle
    data: {}
    target:
      entity_id: light.office_right
  mode: single
- id: '1621805678074'
  alias: Kitchen Cube Shake
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt-aqara/aqara-cube-kitchen
    payload: shake
    value_template: '{{ value_json.action }}'
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.countertop
  mode: single
- id: '1629250564408'
  alias: WLedOffice White Set
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.wledoffice_kelvin
  condition: []
  action:
  - service: light.turn_on
    data_template:
      kelvin: '{{ states(''input_number.wledoffice_kelvin'') | int(1) }}'
    target:
      device_id: 3aafe1d34f701960fe66d2c2da0b05b8
  mode: single
- id: '1629415038976'
  alias: Cube - Living
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt-aqara/aqara-cube-living
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''action_angle''] is defined and trigger.payload_json[''action'']
      is defined and trigger.payload_json[''action''].startswith(''rotate_'') }}'
  action:
  - service: light.turn_on
    target:
      entity_id: light.living_tortue
    data_template:
      brightness: '{{ [[0, 0.2*(trigger.payload_json[''action_angle'']|int) + state_attr(''light.living_tortue'',
        ''brightness'')|int ] | max, 255] | min}}'
  mode: single
- id: '1638765519594'
  alias: Breakfast light
  description: ''
  trigger:
  - platform: time
    at: 07:15:00
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.countertop
      device_id: 2af3fc204f6bf1df64dcc67b9d1f9527
    data:
      brightness_pct: 100
  mode: single
- id: '1639019639828'
  alias: Vicks spot heater On
  description: ''
  trigger:
  - platform: time
    at: 06:00:00
  - platform: state
    entity_id: binary_sensor.is_vick_at_home
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  condition:
  - condition: time
    before: '21:00:00'
    after: 05:59:00
  - condition: state
    entity_id: binary_sensor.is_vick_at_home
    state: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  action:
  - service: climate.set_temperature
    data:
      temperature: 20.5
    target:
      entity_id: climate.0xf8f005fffff483ab
  mode: single
- id: '1639019928666'
  alias: Vick spot heater off
  description: ''
  trigger:
  - platform: time
    at: '19:01:00'
  - platform: state
    entity_id: light.vicks_spot_main_dimmer
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.is_vick_at_home
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  condition:
  - condition: time
    after: '17:30:00'
  action:
  - service: climate.set_temperature
    data:
      temperature: 18
    target:
      entity_id: climate.0xf8f005fffff483ab
  mode: single
- id: '1639235579204'
  alias: Heaters when home is alone
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.is_someone_at_home
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: input_number.set_value
    target:
      entity_id: input_number.main_room_temperature
    data:
      value: 17.5
  mode: single
- id: '1640633309912'
  alias: Hue Tap Buttons
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/hue_tap_switch/action
    id: trigger
  condition: []
  action:
  - service: '{% if trigger.payload == ''toggle'' %}

      light.toggle

      {% elif trigger.payload == ''recall_scene_0'' %}

      light.turn_on

      {% elif trigger.payload == ''recall_scene_1'' %}

      light.turn_off

      {% elif trigger.payload == ''recall_scene_2'' %}

      light.turn_off

      {% endif %}

      '
    data_template:
      entity_id: '{% if trigger.payload == ''toggle'' %} light.light_bedroom_candle
        {% elif trigger.payload == ''recall_scene_0'' %} light.light_bedroom_candle,
        light.bedroom_main_dimmer {% elif trigger.payload == ''recall_scene_1'' %}
        light.light_bedroom_candle, light.bedroom_main_dimmer {% elif trigger.payload
        == ''recall_scene_2'' %} group.lights_interior {% endif %}

        '
  mode: single
- id: '1641237229359'
  alias: Office Cube - Flip
  description: ''
  trigger:
  - platform: mqtt
    payload: flip180
    value_template: '{{ value_json.action }}'
    topic: zigbee2mqtt-aqara/aqara-cube-office
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id:
      - light.wled_segment_1
      - light.wled
      - light.wled_master
  mode: single
- id: '1642108860891'
  alias: Printer Lights when printing
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.printer_vibration
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.printer_vibration
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: '{% if states(''binary_sensor.printer_vibration'') == ''on'' %}

      light.turn_on

      {% else %}

      light.turn_off

      {% endif %}

      '
    target:
      entity_id: light.printer_lights
  mode: single
- id: '1642113839486'
  alias: New Automation
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 8c2c704a6654427fa5c0b593317cb49c
    type: action
    subtype: 'on'
    discovery_id: 0xb4e3f9fffec28918 action_on
    id: button_on
  - platform: device
    domain: mqtt
    device_id: 8c2c704a6654427fa5c0b593317cb49c
    type: action
    subtype: 'off'
    discovery_id: 0xb4e3f9fffec28918 action_off
    id: button_off
  - platform: device
    domain: mqtt
    device_id: 8c2c704a6654427fa5c0b593317cb49c
    type: action
    subtype: brightness_step_up
    discovery_id: 0xb4e3f9fffec28918 action_brightness_step_up
    id: brightness_up
  - platform: device
    domain: mqtt
    device_id: 8c2c704a6654427fa5c0b593317cb49c
    type: action
    subtype: brightness_step_down
    discovery_id: 0xb4e3f9fffec28918 action_brightness_step_down
    id: brightness_down
  - platform: device
    domain: mqtt
    device_id: 8c2c704a6654427fa5c0b593317cb49c
    type: action
    subtype: color_temperature_step_down
    discovery_id: 0xb4e3f9fffec28918 action_color_temperature_step_down
    id: brightness_big_down
  - platform: device
    domain: mqtt
    device_id: 8c2c704a6654427fa5c0b593317cb49c
    type: action
    subtype: color_temperature_step_up
    discovery_id: 0xb4e3f9fffec28918 action_color_temperature_step_up
    id: brightness_big_up
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: '{% if trigger.id == ''button_off'' %}

        0

        {% elif trigger.id == ''brightness_up'' %}

        {{ min(255, (state_attr(''light.counter'',''brightness'') | int) + 32) }}

        {% elif trigger.id == ''brightness_down'' %}

        {{ max(0, (state_attr(''light.counter'',''brightness'') | int) - 32) }}

        {% elif trigger.id == ''brightness_big_up'' %}

        128

        {% elif trigger.id == ''brightness_big_down'' %}

        1

        {% else %}255{% endif %}

        '
      entity_id: light.counter
  mode: single
- id: '1642440511035'
  alias: Printer Cam Flash On-Off
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.printer_vibration
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.printer_vibration
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  condition: []
  action:
  - service: '{% if states(''binary_sensor.printer_vibration'') == ''on'' %}

      light.turn_on

      {% else %}

      light.turn_off

      {% endif %}

      '
    target:
      entity_id: light.flash
  mode: single
