homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 45.5049
  longitude: -73.7142
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction: false

# Enables the frontend
frontend: false

# Enables configuration UI
config: true

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook: false

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

mqtt:
  broker: mqtt

# Weather prediction
sensor:
  - platform: yr
  - platform: openweathermap
    api_key: !secret openweathermap_apikey
    monitored_conditions:
      - weather
  - platform: mqtt
    name: "Temperature"
    state_topic: "office/sensor1"
    unit_of_measurement: '°C'
    value_template: "{{ value_json.temperature }}"
  - platform: mqtt
    name: "Humidity"
    state_topic: "office/sensor1"
    unit_of_measurement: '%'
    value_template: "{{ value_json.humidity }}"

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml


# Example configuration.yaml entry
light:
  platform: limitlessled
  bridges:
    - host: 192.168.1.148
      version: 4
      port: 8899
      groups:
      - number: 1
        type: rgbw
        name: Office
        fade: on
      - number: 2
        type: rgbw
        name: Kitchen
        fade: on
      - number: 4
        type: rgbw
        name: Livingroom
        fade: on
