homeassistant:
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.240.0/24
        - 192.168.1.0/24
        - fd00::/8

default_config:

discovery:
  ignore:
    - homekit

homekit:
  filter:
    exclude_domains:
      - automation
      - script
      - scene
      - lock
      - remote
      - device_tracker
      - binary_sensor
      - sensor
      - select
      - light
    exclude_entity_globs:
      - automation.*
      - script.*
      - scene.*
      - lock.*
      - remote.*
      - device_tracker.*
      - binary_sensor.*
      - sensor.*
      - select.*

frontend:
  themes: !include_dir_merge_named themes

mobile_app:

mqtt:
  device_tracker:
  - name: nico_pixel_office
    state_topic: "ble-presence-office/binary_sensor/nics_pixel_ibeacon_backwards/state"
  - name: nico_pixel_living
    state_topic: "ble-presence-living/binary_sensor/nics_pixel_ibeacon_backwards/state"
  - name: nico_pixel_kitchen
    state_topic: "ble-presence-kitchen/binary_sensor/nics_pixel_ibeacon_backwards/state"
  - name: nico_pixel_bedroom
    state_topic: "ble-presence-bedroom/binary_sensor/nics_pixel_ibeacon_backwards/state"
  sensor:
  - name: "Climate Bedroom Raw PIHeat"
    unique_id: climate_bedroom_raw_piheat
    unit_of_measurement: '%'
    json_attributes_topic: zigbee2mqtt/climate_bedroom
    state_topic: zigbee2mqtt/climate_bedroom
    json_attributes_template: '{{ value_json.pi_heating_demand }}'
    value_template: '{{ value_json.pi_heating_demand }}'
    # MQTT publish: topic 'zigbee2mqtt/climate_office', payload '{"humidity":null,"keypad_lockout":0,"linkquality":174,"local_temperature":22,"occupied_heating_setpoint":21.5,"operation":"heating","pi_heating_demand":7,"running_state":"heat","system_mode":"heat"}'
  - name: "Climate Vicks Raw PIHeat"
    unique_id: climate_vicks_raw_piheat
    unit_of_measurement: '%'
    json_attributes_topic: zigbee2mqtt/climate_vicks
    state_topic: zigbee2mqtt/climate_vicks
    json_attributes_template: '{{ value_json.pi_heating_demand }}'
    value_template: '{{ value_json.pi_heating_demand }}'
    # MQTT publish: topic 'zigbee2mqtt/climate_office', payload '{"humidity":null,"keypad_lockout":0,"linkquality":174,"local_temperature":22,"occupied_heating_setpoint":21.5,"operation":"heating","pi_heating_demand":7,"running_state":"heat","system_mode":"heat"}'




logger:
  default: warning
  logs:
    homeassistant.components.recorder: warning
    paho.mqtt.client: warning
    homeassistant.components.mqtt: warning
    homeassistant.core: warning
    awesomeversion: warning
    homeassistant.components.yeelight: warning
    async_upnp_client.traffic.ssdp: warning
    homeassistant.components.wled: warning
    homeassistant.components.filter: warning
    yeelight.aio: warning
    aiohue.v2: warning
    aiohue.v2.events: warning
    zeroconf: warning
    # homeassistant.components.websocket_api.http.connection: warning

# Enables configuration UI
config:
system_health:
api:

lovelace:
  mode: storage

recorder:
   purge_keep_days: 5

http:
  # Secrets are defined in the file secrets.yaml
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  use_x_forwarded_for: true
  trusted_proxies:
  - 172.18.0.0/16
  - 172.19.0.0/16
  - 172.20.0.0/16
  - 172.21.0.0/16
  - 192.168.240.1

binary_sensor:
  - platform: template
    sensors:
      is_nico_at_home_from_file:
        value_template: >-
          {%- if 
          states('binary_sensor.nic_s_pixel_kitchen_ibeacon_backwards') == 'on' or
          states('binary_sensor.nic_s_pixel_vicks_ibeacon_backwards') == 'on' or
          states('binary_sensor.nic_s_pixel_bedroom_ibeacon_backwards') == 'on' or
          states('binary_sensor.nic_s_pixel_office_ibeacon_backwards') == 'on' or
          states('binary_sensor.nic_s_pixel_printer_ibeacon_backwards') == 'on' or
          states('binary_sensor.nic_s_pixel_bedroom32_ibeacon_backwards') == 'on'
          -%}
          on
          {%- else -%}
          off
          {%- endif  %}
  - platform: template
    sensors:
      is_vick_at_home_from_file:
        value_template: >-
          {%- if 
          states('binary_sensor.vick_s_pixel_kitchen_ibeacon_backwards') == 'on' or
          states('binary_sensor.vick_s_pixel_vicks_ibeacon_backwards') == 'on' or
          states('binary_sensor.vick_s_pixel_bedroom_ibeacon_backwards') == 'on' or
          states('binary_sensor.vick_s_pixel_office_ibeacon_backwards') == 'on' or
          states('binary_sensor.vick_s_pixel_printer_ibeacon_backwards') == 'on' or
          states('binary_sensor.vick_s_pixel_bedroom32_ibeacon_backwards') == 'on'
          -%}
          on
          {%- else -%}
          off
          {%- endif  %}          
  - platform: template
    sensors:
      is_someone_at_home_from_file:
        value_template: >-
          {%- if 
          states('binary_sensor.is_vick_at_home') == 'on' or
          states('binary_sensor.is_nico_at_home') == 'on'
          -%}
          on
          {%- else -%}
          off
          {%- endif  %}

conversation: # Allows you to issue voice commands from the frontend in enabled browsers
history: # Enables support for tracking state changes over time
logbook: # View all events in a logbook
  include:
    domains:
    - automation
    - climate
    - input_number

map: # Enables a map showing the location of tracked devices
sun: # Track the sun
cloud:
tts: # Text to speech
  - platform: google_translate


telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_fullum_bot_token
    allowed_chat_ids:
      - !secret telegram_fullum_bot_chat_id
      - !secret telegram_fullumbasement_bot_chat_id

notify:
  - platform: telegram
    name: "fullumcoowners"
    chat_id: !secret telegram_fullumbasement_bot_chat_id

  - platform: telegram
    name: "home"
    chat_id: !secret telegram_fullum_bot_chat_id

weather: !include weather.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
timer: !include timers.yaml
climate: !include climate.yaml
rest_command: !include rest_commands.yaml
light: !include lights.yaml
zone: !include zones.yaml

input_number:
input_select:
schedule:
input_boolean:

yeelight: !include yeelight.yaml


# influxdb:
#  api_version: 2
#  host: 192.168.1.157
#  port: 8086
#  ssl: false
#  verify_ssl: false
#  organization: homeOrg
#  bucket: homeBucket
#  token: !secret influxdb_token
#  precision: s
#  default_measurement: _default
#  tags:
#    source: HA
