homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 45.5303786
  longitude: -73.5545572
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 15
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Montreal
  # Customization file
  customize: !include customize.yaml
  auth_providers:
  - type: homeassistant
  - type: trusted_networks
    trusted_networks:
    - 192.168.0.0/24
    - fd00::/8
  - type: legacy_api_password
    api_password: !secret http_password

# Show links to resources in log and frontend
# introduction: false

logger:
  default: warning
  logs:
    homeassistant.components.device_tracker: warning
    homeassistant.components.mqtt: info
    homeassistant.components.automations: info
    homeassistant.components.automation: info

# Enables configuration UI
config:
system_health:
api:

lovelace:
  mode: yaml

recorder:
  purge_interval: 1
  purge_keep_days: 5
  exclude:
    entities:
    - automation.thermodev_01
    - automation.thermodev_01_climate
    - automation.thermodev_02
    - automation.thermodev_heartbeat
    domains:
    - automation

history_graph:
  temperature_96:
    name: Temperatures
    entities:
     - sensor.living_temperature
     - sensor.office_temperature
     - binary_sensor.living_heater_state
     - binary_sensor.office_heater_state
     - group.presence
    hours_to_show: 96
  temperature_6:
    name: Temperatures 6 hours
    entities:
     - sensor.living_temperature
     - sensor.office_temperature
     - binary_sensor.living_heater_state
     - binary_sensor.office_heater_state
     - group.presence
    hours_to_show: 6

http:
  # Secrets are defined in the file secrets.yaml
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

binary_sensor:
  - platform: mqtt
    name: Office heater state
    state_topic: "/ThermoDev/Sensor01/CurrentState"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: Living heater state
    state_topic: "/ThermoDev/Sensor02/CurrentState"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: template
    sensors:
      high:
        value_template: "{{(states('sensor.raw_basement_humidity') | float > 55) or (states('sensor.raw_basement_temperature') | float > 25) }}"
      low:
        value_template: "{{(states('sensor.raw_basement_humidity') | float < 10) or (states('sensor.raw_basement_temperature') | float < 10)}}"

discovery:
  ignore:
  - yeelight # Discover some devices automatically

conversation: # Allows you to issue voice commands from the frontend in enabled browsers
history: # Enables support for tracking state changes over time
logbook: # View all events in a logbook
map: # Enables a map showing the location of tracked devices
sun: # Track the sun
cloud:
tts: # Text to speech
 - platform: google_translate

mqtt:
  broker: mosquitto
 # broker: 192.168.1.106

weather: !include weather.yaml
camera: !include camera.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations
device_tracker: !include device_trackers.yaml
climate: !include climate.yaml
rest_command: !include rest_commands.yaml
light: !include lights.yaml
zone: !include zones.yaml
# Example configuration.yaml entry

input_text:
  current_scene:
    name: Current Scene
  device_heartbeat_thermodev:
    name: ThermoDev HeartBeat

input_number:
  living_temperature_slider:
    name: Living Slider °C
    initial: 18
    min: 17
    max: 23
    step: .5
  office_temperature_slider:
    name: Office Slider °C
    initial: 18
    min: 17
    max: 23
    step: .5
  home_alone_temperature_slider:
    name: Home Alone Temp
    initial: 17
    min: 16
    max: 23
    step: .5
  at_home_temperature_slider:
    name: Welcoming Temp
    initial: 20
    min: 17
    max: 23
    step: .5
  at_home_sleeping:
    name: During the night
    initial: 18
    min: 17
    max: 23
    step: .5
  moes_dimmer_clickcounter:
    name: moes dimmer dev click counter
    initial: 0
    max: 20
    min: 0
    step: 1


yeelight: !include yeelight.yaml