- platform: ping
  count: 5
  consider_home: 0:10
  new_device_defaults:
    track_new_devices: true
    hide_if_away: false
  hosts:
    nico_moto5_ping: 192.168.1.12
    vsmbr_phone: 192.168.1.214
#    vsmbr_laptop: 192.168.1.127
#    pepo_android: 192.168.1.105
