- platform: mqtt
  devices:
    nico_pixel_office: "ble-presence-office/binary_sensor/nics_pixel_ibeacon_backwards/state"
    nico_pixel_living: "ble-presence-living/binary_sensor/nics_pixel_ibeacon_backwards/state"
    nico_pixel_kitchen: "ble-presence-kitchen/binary_sensor/nics_pixel_ibeacon_backwards/state"
    nico_pixel_bedroom: "ble-presence-bedroom/binary_sensor/nics_pixel_ibeacon_backwards/state"
  payload_home: ON
  payload_not_home: OFF
  source_type: bluetooth_le
- platform: mqtt
  devices:
    nico_pixel_office: "ble-presence-office/binary_sensor/vicks_velvet_ibeacon_backwards/state"
    nico_pixel_living: "ble-presence-living/binary_sensor/vicks_velvet_ibeacon_backwards/state"
    nico_pixel_kitchen: "ble-presence-kitchen/binary_sensor/vicks_velvet_ibeacon_backwards/state"
    nico_pixel_bedroom: "ble-presence-bedroom/binary_sensor/vicks_velvet_ibeacon_backwards/state"
  payload_home: ON
  payload_not_home: OFF
  source_type: bluetooth_le
- platform: mqtt
  devices:
    nico_pixel_custom: "custom-presence/nico"
  payload_home: home
  payload_not_home: not_home
  source_type: bluetooth_le
