default_view:
  view: yes
  entities:
    - group.all_lights
    - group.kitchen
    - group.countertop
    - group.living
    - group.climate
    - group.office
    - group.debugpanel
    - group.debug
    - group.presence
kitchen:
  name: Kitchen
  view: no
  entities:
    - light.kitchen
    - light.countertop
    - group.kitchen_climate
living:
  name: Living
  view: no
  entities:
    - light.living_moon
    - light.couch
    - group.living_climate
climate:
  name: Climate
  view: no
  entities:
    - sun.sun
    - sensor.owm_condition
    - sensor.yr_symbol
    - group.living_climate
    - group.office_climate
    - group.kitchen_climate

living_climate:
  view: no
  entities:
    - sensor.living_temperature
    - sensor.living_humidity
    - binary_sensor.living_heater_state
    - input_number.living_temperature_slider
    - group.presence

office_climate:
  view: no
  entities:
    - sensor.office_temperature
    - sensor.office_humidity
    - binary_sensor.office_heater_state
    - input_number.office_temperature_slider
    - group.presence

office:
  name: Office
  view: no
  entities:
    - light.office
    - light.office_yee
    - group.office_climate

tab_climate:
  name: Climate
  view: yes
  entities:
    - group.office_climate
    - group.living_climate

debugpanel:
  name: Debug
  view: no
  entities:
    - sensor.living_temperature
    - input_text.current_scene

scenes:
  name: Scenes
  view: yes
  entities:
    - scene.alone__evening
    - scene.alone__late
    - scene.sleeping__not_alone
    - scene.someone_got_home
    - scene.all_full
presence:
  name: Presence
  entities:
    - sensor.nico_moto5_battery
    - device_tracker.nico_moto5
    - device_tracker.vsmbr
    - device_tracker.nico_moto5_ping
    - group.all_devices
lights_interior:
  name: Interior lights
  entities:
    - light.office
    - light.office_yee
    - light.bedroom_lamp
    - light.kitchen
    - light.couch
    - light.countertop
    - light.living_moon
