lights_interior:
  name: Interior lights
  entities:
    - light.light_bedroom_candle_light
    - light.office_yee
    - light.kitchen_lamp
    - light.office_right
    - light.living_tortue
    - light.wledoffice
    - light.counter
    - light.kitchen_main
    - light.dimmer_vicks_spot
    - light.wled
    - light.wled_master
    - light.printer_lights
    - light.flash
    - light.living_corner_lamp
    - light.office_lamp_left_side
    - light.kitchen_countertop

lights_exterior:
  name: Exterior Lights
  entities:
    - light.yeelight_color_0x7e7b341
