default_view:
  view: yes
  entities:
    - group.all_lights
    - group.kitchen
    - group.countertop
    - group.living
    - group.climate
    - group.office
    - group.debugpanel
    - group.debug
    - group.presence
kitchen:
  name: Kitchen
  view: no
  entities:
    - light.kitchen
    - light.countertop
    - group.kitchen_climate
living:
  name: Living
  view: no
  entities:
    - light.living_moon
    - light.couch
    - group.living_climate
climate:
  name: Climate
  view: no
  entities:
    - sun.sun
    - group.living_climate
    - group.office_climate
    - group.kitchen_climate

living_climate:
  view: no
  entities:
    - climate.living
    - input_number.living_temperature
    - switch.living_heater
    - sensor.living_temperature_setpoint
office_climate:
  view: no
  entities:
    - climate.office
    - input_number.office_temperature
    - switch.office_heater
    - sensor.office_temperature_setpoint
kitchen_climate:
  view: no
  entities:
    - climate.kitchen
    - input_number.kitchen_temperature
    - switch.kitchen_heater
    - sensor.kitchen_temperature_setpoint

office:
  name: Office
  view: no
  entities:
    - light.office
    - light.office_yee
    - group.office_climate
debugpanel:
  name: Debug
  view: no
  entities:
    - sensor.living_temperature_setpoint
    - sensor.office_temperature_setpoint
    - sensor.kitchen_temperature_setpoint
    - input_text.current_scene
scenes:
  name: Scenes
  view: yes
  entities:
    - scene.alone__evening
    - scene.alone__late
    - scene.sleeping__not_alone
    - scene.someone_got_home
    - scene.all_full
presence:
  name: Presence
  entities:
    - sensor.nico_moto5_battery
    - device_tracker.nico_moto5
    - group.all_devices
lights_interior:
  name: Interior lights
  entities:
    - light.office
    - light.office_yee
    - light.bedroom
    - light.kitchen
    - light.couch
    - light.countertop
    - light.living_moon
