default_view:
  view: yes
  entities:
    - group.all_lights
    - group.kitchen
    - group.living
    - group.climate
    - group.office
    - group.debugpanel
    - group.debug
kitchen:
  name: Kitchen
  view: no
  entities:
    - light.kitchen
living:
  name: Living
  view: no
  entities:
    - light.living_moon
    - light.couch
    - climate.living
    - switch.living_heater
    - input_number.living_temperature
    - sensor.setpoint_status
climate:
  name: Climate
  view: no
  entities:
    - sun.sun
    - group.living_climate
living_climate:
  view: no
  entities:
    - climate.living
    - input_number.living_temperature
    - switch.living_heater
    - sensor.living_temperature_setpoint
office_climate:
  view: no
  entities:
    - climate.office
    - input_number.office_temperature
    - switch.office_heater
    - sensor.office_temperature_setpoint

office:
  name: Office
  view: no
  entities:
    - light.office
    - light.office_yee
    - group.office_climate
debugpanel:
  name: Debug
  view: no
  entities:
    - sensor.living_temperature_setpoint
    - sensor.office_temperature_setpoint
    - sensor.kitchen_temperature_setpoint
