lights_interior:
  name: Interior lights
  entities:
    - light.light_bedroom_candle_light
    - light.office_yee
    - light.kitchen_lamp
    - light.office_2
    - light.living_moon
    - light.living_tortue
    - light.wled
    - light.space_lamp_light
    - light.countertop
    - light.kitchen_main
    - light.dimmer_vicks_spot

lights_exterior:
  name: Exterior Lights
  entities:
    - light.front_door
