presence:
  name: Presence
  entities:
    - sensor.nico_moto5_battery
    - device_tracker.nico_moto5
    - device_tracker.vsmbr_phone
    - device_tracker.nico_moto5_ping
    - group.all_devices

lights_interior:
  name: Interior lights
  entities:
    - light.office_back_lamp
    - light.light_bedroom_candle_light
    - light.office_yee
    - light.kitchen_lamp
    - light.office_2
    - light.living_moon
    - light.living_tortue
    - light.office_ambient_lamp
    - light.wled
    - light.vicks_spot_main_light_light
    - light.light_bedroom_candle_light
    - light.space_lamp_light
    - light.countertop
    - light.kitchen_main
    - light.dimmer_vicks_spot

lights_exterior:
  name: Exterior Lights
  entities:
    - light.front_door
