default_view:
  view: yes
  entities:
    - group.main

main:
  view: no
  name: Main
  control: hidden
  entities:
    - scene.someone_got_home
    - scene.all_full
    - scene.chillin
    - scene.morning
    - scene.movies
    - group.all_lights
    - group.presence
    - input_number.at_home_temperature_slider
    - sensor.average_temperature

tab_cameras:
  name: Cameras
  view: yes
  entities:
    - camera.door
    - camera.kitchen

lights:
  view: yes
  name: Lights
  entities:
    - group.lights_interior
    - group.scenes

kitchen:
  name: Kitchen
  view: no
  entities:
    - light.kitchen
    - light.countertop
    - group.kitchen_climate
living:
  name: Living
  view: no
  entities:
    - light.living_moon
    - light.couch
    - group.living_climate

living_climate:
  view: no
  name: Living ºC
  entities:
    - sensor.living_temperature
    - sensor.living_humidity
    - binary_sensor.living_heater_state
    - input_number.living_temperature_slider
    - group.presence

office_climate:
  name: Office ºC
  view: no
  entities:
    - sensor.office_temperature
    - sensor.office_humidity
    - binary_sensor.office_heater_state
    - input_number.office_temperature_slider
    - group.presence

home_climate:
  name: Automation
  view: no
  entities:
    - input_number.at_home_temperature_slider
    - input_number.home_alone_temperature_slider
    - input_number.at_home_sleeping

home_climate_sensors:
  name: Sensors
  view: no
  entities:
   - sensor.office_temperature
   - sensor.living_temperature

office:
  name: Office
  view: no
  entities:
    - light.office
    - light.office_yee
    - group.office_climate

tab_climate:
  name: Climate
  view: yes
  entities:
    - sun.sun
    - group.office_climate
    - group.living_climate
    - group.home_climate
    - group.presence
    - input_text.device_heartbeat_thermodev
    - group.home_climate_sensors

debugpanel:
  name: Debug
  view: no
  entities:
    - sensor.living_temperature
    - input_text.current_scene

scenes:
  name: Scenes
  view: no
  entities:
    - scene.morning
    - scene.alone__evening
    - scene.alone__late
    - scene.someone_got_home
    - scene.all_full
    - scene.chillin
    - scene.movies
    - scene.sleeping__not_alone

tab_scenes:
  name: Scenes
  view: yes
  entities:
    - scene.alone__evening
    - scene.alone__late
    - scene.sleeping__not_alone
    - scene.someone_got_home
    - scene.all_full
    - scene.chillin
    - scene.morning

presence:
  name: Presence
  entities:
    - sensor.nico_moto5_battery
    - device_tracker.nico_moto5
    - device_tracker.vsmbr_phone
    - device_tracker.nico_moto5_ping
    - group.all_devices

lights_interior:
  name: Interior lights
  entities:
    - light.office
    - light.office_yee
    - light.kitchen
    - light.couch
    - light.countertop
    - light.living_moon

lights_moesdimmer01:
  name: "Dimmable 01"
  entities:
  - light.office
  - light.couch
  - light.countertop

lights_moesdimmer02:
  name: "Dimmable 02"
  entities:
  - light.office
  - light.kitchen
  - light.countertop
  - light.couch
  - light.living_moon
  - light.bedroom_lamp
