lights_interior:
  name: Interior lights
  entities:
    - light.light_bedroom_candle_light
    - light.office_yee
    - light.kitchen_lamp
    - light.office_right
    - light.living_tortue
    - light.wledoffice
    - light.countertop
    - light.kitchen_main
    - light.dimmer_vicks_spot
    - light.wled
    - light.printer_lights

lights_exterior:
  name: Exterior Lights
  entities:
    - light.front_door
