default_view:
  view: yes
  entities:
    - group.kitchen
    - group.living
    - group.office
    - group.bedroom
    - group.guestroom

weather:
  name: Weather in Montréal
  entities:
    -  sensor.owm_condition

kitchen:
  name: Kitchen
  entities:
    - light.kitchen

living:
  name: Living room
  entities:
    - light.livingroom

office:
  name: Office
  entities:
    - light.office
    - sensor.office_humidity
    - sensor.office_temperature
    - switch.dummy_switch_for_scripts

bedroom:
  name: Main Bedroom
  entities:
    - sun.sun

guestroom:
  name: Guest bedroom
