- platform: limitlessled
  bridges:
   - host: 192.168.1.148
     version: 4
     port: 8899
     groups:
      - number: 1
        type: rgbw
        name: Office
        fade: on
      - number: 2
        type: rgbw
        name: Office Ceiling
        fade: on
      - number: 3
        type: rgbw
        name: Countertop
        fade: on
      - number: 4
        type: rgbw
        name: Couch
        fade: on
- platform: yeelight
  devices:
    192.168.1.232:
      name: Office Yee
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: false #(defaults to false)
      model: color2
    192.168.1.147:
      name: Living Moon
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: false #(defaults to false)
      model: color2
    192.168.1.234:
      name: Kitchen
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: false #(defaults to false)
      model: color2
# See https://www.home-assistant.io/components/light.mqtt/#brightness_command_topic

- platform: mqtt
  name: "MoesDimmer Strips"
  command_topic: "cmnd/sonoff/switch/strips/POWER"
  state_topic: stat/sonoff/switch/strips/RESULT/filtered
  state_value_template: "{{value_json.POWER}}"
  brightness_command_topic: "cmnd/sonoff/switch/strips/DIMMER"
  brightness_state_topic: stat/sonoff/switch/strips/RESULT/filtered
  brightness_scale: 99
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/sonoff/switch/strips/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "MoesDimmer02"
  command_topic: "cmnd/sonoff/switch/office/POWER"
  state_topic: "stat/sonoff/switch/office/RESULT/filtered"
  state_value_template: "{{value_json.POWER}}"
  brightness_command_topic: "cmnd/sonoff/switch/office/DIMMER"
  brightness_state_topic: "stat/sonoff/switch/office/RESULT/filtered"
  brightness_scale: 99
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/sonoff/switch/office/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "MoesDimmer Dev"
  command_topic: "cmnd/sonoff/switch/dev/POWER"
  state_topic: "stat/sonoff/switch/dev/RESULT/filtered"
  state_value_template: "{{value_json.POWER}}"
  brightness_command_topic: "cmnd/sonoff/switch/dev/DIMMER"
  brightness_state_topic: "stat/sonoff/switch/dev/RESULT/filtered"
  brightness_scale: 99
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/sonoff/switch/dev/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false  