- platform: limitlessled
  bridges:
   - host: 192.168.1.148
     version: 4
     port: 8899
     groups:
      - number: 1
        type: rgbw
        name: Office
        fade: on
      - number: 2
        type: rgbw
        name: Kitchen
        fade: on
      - number: 3
        type: rgbw
        name: Countertop
        fade: on
      - number: 4
        type: rgbw
        name: Couch
        fade: on
- platform: yeelight
  devices:
    192.168.1.232:
      name: Office Yee
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: True #(defaults to True)
    192.168.1.147:
      name: Living Moon
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: True #(defaults to True)
    192.168.1.234:
      name: Bedroom lamp
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: True #(defaults to True)
# See https://www.home-assistant.io/components/light.mqtt/#brightness_command_topic
