# zoneminder_stop:
#   url: 'https://192.168.1.106:8180/zm/api/states/change/stop.json'
#   method: POST
# zoneminder_start:
#   url: 'https://192.168.1.106:8180/zm/api/states/change/start.json'
#   method: POST

let_nico_know:
    url: !secret one_slack_channel
    method: POST
    payload: '{"text":"{{ text }}" }'
    content_type:  'application/json; charset=utf-8'

let_nico_know_debug:
    url: http://locative-endpoint:3998/
    method: POST
    payload: '{"text":"{{ text }}" }'
    content_type:  'application/json; charset=utf-8'
