- name: Alone - late
  entities:
    light.living_moon:
      state: off
    light.office_yee:
      state: on
      brightness: 43
      color_temp: 324
    light.bedroom_lamp:
      state: on
      brightness: 84
      color_temp: 324
    light.office:
      state: off
    light.couch:
      state: on
      brightness: 101
    light.kitchen:
      state: off
- name: Alone - evening
  entities:
    light.kitchen:
      state: on
      brightness: 132
    light.office:
      state: on
      brightness: 61
    light.couch:
      state: on
      brightness: 102
    light.office_yee:
      state: on
      brightness: 59
      color_temp: 358
    light.living_moon:
      state: on
      brightness: 255
      color_temp: 324
    light.bedroom_lamp:
      state: on
      brightness: 82
      color_temp: 393
