- id: '1577673229045'
  name: Saul Goodman
  entities:
    light.couch:
      assumed_state: true
      brightness: 133
      effect_list:
      - colorloop
      - night
      - white
      friendly_name: Couch
      state: 'on'
      supported_features: 61
    light.countertop:
      assumed_state: true
      brightness: 224
      effect_list:
      - colorloop
      - night
      - white
      friendly_name: Countertop
      state: 'on'
      supported_features: 61
    light.kitchen:
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Slow Temp
      - Stop
      friendly_name: Kitchen
      max_mireds: 370
      min_mireds: 153
      state: unavailable
      supported_features: 63
    light.kitchen_wall:
      brightness: 255
      color_temp: 370
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Slow Temp
      - Stop
      friendly_name: Kitchen Wall
      hs_color:
      - 75.273
      - 43.137
      max_mireds: 370
      min_mireds: 153
      rgb_color:
      - 226
      - 255
      - 145
      state: 'on'
      supported_features: 63
      xy_color:
      - 0.361
      - 0.459
    light.living_tortue:
      brightness: 3
      color_temp: 370
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Slow Temp
      - Stop
      friendly_name: Living Tortue
      hs_color:
      - 28.391
      - 65.659
      max_mireds: 370
      min_mireds: 153
      rgb_color:
      - 255
      - 166
      - 87
      state: 'on'
      supported_features: 63
      xy_color:
      - 0.526
      - 0.387
    light.office:
      assumed_state: true
      brightness: 136
      effect_list:
      - colorloop
      - night
      - white
      friendly_name: Office
      state: 'on'
      supported_features: 61
    light.office_ambient_lamp:
      brightness: 135
      color_temp: 356
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Slow Temp
      - Stop
      friendly_name: Office ambient lamp
      hs_color:
      - 28.172
      - 62.378
      max_mireds: 370
      min_mireds: 153
      rgb_color:
      - 255
      - 170
      - 95
      state: 'on'
      supported_features: 63
      xy_color:
      - 0.516
      - 0.386
- name: Chillin
  entities:
    light.couch:
      state: on
      brightness: 124
    light.bedroom_wardrobe:
      state: on
      brightness: 27
      color_temp: 370 
    light.countertop:
      state: on
      brightness: 255
    light.kitchen:
      state: on
      brightness: 27
      color_temp: 370
    light.office:
      state: on
      brightness: 109
    light.office_ambient_lamp:
      state: on
      brightness: 109
    light.living_moon:
      state: on
      brightness: 161
      color_temp: 370
    light.office_yee:
      state: on
      brightness: 125
      color_temp: 370
    light.living_tortue:
      state: on
      brightness: 125
      color_temp: 370    
- name: Movies
  entities:
    light.couch:
      state: on
      brightness: 1
    light.countertop:
      state: on
      brightness: 1
    light.kitchen:
      state: off
    light.office:
      state: on
      brightness: 1
    light.living_moon:
      state: off
    light.office_yee:
      state: on
      brightness: 1
      color_temp: 370
    light.living_tortue:
      state: on
      brightness: 10
      color_temp: 370      
- name: All full
  entities:
    light.office_yee:
      state: on
      brightness: 255
      color_temp: 335
    light.kitchen:
      state: on
      brightness: 255
      color_temp: 335
    light.living_moon:
      state: on
      brightness: 255
      color_temp: 588
    light.moesdimmer01:
      state: on
      brightness: 255
    light.moesdimmer02:
      state: on
      brightness: 255
    light.living_tortue:
      state: on
      brightness: 255
      color_temp: 370

- name: Red ambient
  entities:
    light.office:
      state: on
      brightness: 1
    light.countertop:
      state: on
      brightness: 165
    light.couch:
      state: on
      brightness: 191
    light.kitchen:
      state: on
      brightness: 61
      color_temp: 272
    light.office_yee:
      state: on
      brightness: 3
      color_temp: 370
    light.living_moon:
      state: on
      brightness: 97
      color_temp: 393
- name: Nico Compu
  entities:
    light.front_door:
      state: 'on'
      brightness: 190
    light.countertop:
      state: 'on'
      brightness: 255
    light.couch:
      state: 'on'
      brightness: 255
    light.office: 'off'
    light.office_yee:
      state: 'on'
      brightness: 255
      color_temp: 370
    light.bedroom_wardrobe:
      state: on
      brightness: 10
      color_temp: 370
    light.kitchen: 'off'
    light.living_moon: 'off'
    light.office_ambient_lamp:
      state: 'on'
      brightness: 56
      color_temp: 370
    light.living_tortue:
      state: on
      brightness: 125
      color_temp: 370
- name: Medium
  entities:
    light.office:
      state: on
      brightness: 255
    light.couch:
      state: on
      brightness: 109
    light.front_door:
      state: on
      brightness: 190
    light.countertop:
      state: on
      brightness: 142
    light.office_yee:
      state: on
      brightness: 54
      color_temp: 332
    light.living_moon:
      state: on
      brightness: 74
      color_temp: 349
    light.office_ambient_lamp:
      state: on
      brightness: 125
      color_temp: 325
    light.kitchen:
      state: on
      brightness: 171
      color_temp: 319
    light.bedroom_wardrobe:
      state: on
      brightness: 171
      color_temp: 319
    light.living_tortue:
      state: on
      brightness: 23
      color_temp: 360

- name: Alone - late
  entities:
    light.office_yee: off
    light.bedroom_wardrobe:
      state: on
      brightness: 84
      color_temp: 370
    light.living_tortue: off
    light.living_moon:
      state: off
    light.office_ambient_light:
      state: on
      brightness: 20
      color_temp: 324
    light.office:
      state: on
      brightness: 60
    light.couch:
      state: on
      brightness: 50
    light.countertop:
      state: on
      brightness: 50
    light.kitchen:
      state: off

- name: Alone - evening
  entities:
    light.kitchen:
      state: on
      brightness: 132
    light.office:
      state: on
      brightness: 255
    light.couch:
      state: on
      brightness: 102
    light.countertop:
      state: on
      brightness: 102
    light.office_yee: off
    light.bedroom_wardrobe: off
    light.office_ambient_light:
      state: on
      brightness: 59
      color_temp: 358
    light.living_moon:
      state: off
    light.living_tortue:
        state: off

- name: Alarm
  entities:
    light.office_yee:
      state: on
      effect: "Police"
      brightness: 255
    light.countertop:
      state: on
      brightness: 255
    light.kitchen:
      state: on
      brightness: 255
    light.couch:
      state: on
      brightness: 255
    light.office:
      state: on
      brightness: 255
    light.living_moon:
      state: on
      effect: "Police"
      brightness: 255
    light.living_tortue:
      state: on
      effect: "Police"
      brightness: 255
    light.bedroom_wardrobe:
      state: on
      brightness: 255
      effect: "Police"


- name: Someone got home
  entities:
    light.bedroom_wardrobe:
      state: on
      brightness: 128
      color: 370
    light.living_tortue:
      state: on
      brightness: 23
      color_temp: 360
