- name: Alone - late
  entities:
    light.living_moon:
      state: off
    light.office_yee:
      state: on
      brightness: 20
      color_temp: 324
    light.bedroom_lamp:
      state: off
    light.office:
      state: off
    light.couch:
      state: on
      brightness: 50
    light.countertop:
      state: on
      brightness: 50
    light.kitchen:
      state: off

- name: Alone - evening
  entities:
    light.kitchen:
      state: on
      brightness: 132
    light.office:
      state: on
      brightness: 61
    light.couch:
      state: on
      brightness: 102
    light.countertop:
      state: on
      brightness: 102
    light.office_yee:
      state: on
      brightness: 59
      color_temp: 358
    light.living_moon:
      state: off
    # light.bedroom_lamp:
    #   state: on
    #   brightness: 82
    #   color_temp: 370

- name: Sleeping - not alone
  entities:
    light.office:
      state: off
    light.countertop:
      state: off
    light.kitchen:
      state: off
    light.couch:
      state: on
      brightness: 1
    light.living_moon:
      state: off
    light.bedroom_lamp:
      state: off
    light.office_yee:
      state: off

- name: Someone got home
  entities:
    light.office:
      state: on
      brightness: 117
    light.countertop:
      state: on
      brightness: 255
    light.kitchen:
      state: on
      brightness: 255
    light.couch:
      state: on
      brightness: 255
    light.living_moon:
      state: on
      brightness: 130
      color_temp: 588
    light.bedroom_lamp:
      state: on
      brightness: 41
      color_temp: 370
    light.office_yee:
      state: on
      brightness: 97
      color_temp: 358

- name: All full
  entities:
    light.office_yee:
      state: on
      brightness: 186
      color_temp: 335
    light.bedroom_lamp:
      state: on
      brightness: 255
      color_temp: 370
    light.countertop:
      state: on
      brightness: 255
    light.kitchen:
      state: on
      brightness: 255
    light.couch:
      state: on
      brightness: 255
    light.office:
      state: on
      brightness: 255
    light.living_moon:
      state: on
      brightness: 255
      color_temp: 588

- name: Chillin
  entities:
    light.couch:
      state: on
      brightness: 124
    light.countertop:
      state: on
      brightness: 255
    light.kitchen:
      state: on
      brightness: 27
    light.office:
      state: on
      brightness: 109
    light.bedroom_lamp:
      state: on
      brightness: 102
      color_temp: 370
    light.living_moon:
      state: on
      brightness: 161
      color_temp: 528
    light.office_yee:
      state: on
      brightness: 125
      color_temp: 370

- name: Movies
  entities:
    light.couch:
      state: on
      brightness: 1
    light.countertop:
      state: on
      brightness: 1
    light.kitchen:
      state: off
    light.office:
      state: on
      brightness: 1
    light.bedroom_lamp:
      state: on
      brightness: 1
      color_temp: 370
    light.living_moon:
      state: off
    light.office_yee:
      state: on
      brightness: 1
      color_temp: 370


- name: Morning
  entities:
    light.office_yee:
      state: off
    light.bedroom_lamp:
      state: off
    light.living_moon:
      state: off
    light.couch:
      state: off
    light.office:
      state: off
    light.kitchen:
      state: on
      brightness: 155
    light.countertop:
      state: on
      brightness: 255

- name: Alarm
  entities:
    light.office_yee:
      state: on
      effect: "Police"
    light.countertop:
      state: on
      brightness: 255
    light.kitchen:
      state: on
      brightness: 255
    light.couch:
      state: on
      brightness: 255
    light.office:
      state: on
      brightness: 255
    light.bedroom_lamp:
      state: on
      effect: "Police"
    light.living_moon:
      state: on
      effect: "Police"
