- name: Chillin
  entities:
    light.couch:
      state: true
      brightness: 124
    light.countertop:
      state: true
      brightness: 255
    light.kitchen:
      state: true
      brightness: 27
      color_temp: 370
    light.office:
      state: true
      brightness: 109
    light.living_moon:
      state: true
      brightness: 161
      color_temp: 370
    light.office_yee:
      state: true
      brightness: 125
      color_temp: 370
    light.living_tortue:
      state: true
      brightness: 125
      color_temp: 370
  id: b0056a16eea4493a80a9408d4370b5be
- name: Movies
  entities:
    light.couch:
      state: true
      brightness: 1
    light.countertop:
      state: true
      brightness: 1
    light.kitchen:
      state: false
    light.office:
      state: true
      brightness: 1
    light.living_moon:
      state: false
    light.office_yee:
      state: true
      brightness: 1
      color_temp: 370
    light.living_tortue:
      state: true
      brightness: 10
      color_temp: 370
  id: f909b843139d4da49e647779bbed5645
- name: All full
  entities:
    light.office_yee:
      state: true
      brightness: 255
      color_temp: 335
    light.kitchen:
      state: true
      brightness: 255
      color_temp: 335
    light.living_moon:
      state: true
      brightness: 255
      color_temp: 588
    light.living_tortue:
      state: true
      brightness: 255
      color_temp: 370
  id: 3e67ccf6b7ef4bc19368a8a15d26e6f2
- name: Red ambient
  entities:
    light.office:
      state: true
      brightness: 1
    light.countertop:
      state: true
      brightness: 165
    light.couch:
      state: true
      brightness: 191
    light.kitchen:
      state: true
      brightness: 61
      color_temp: 272
    light.office_yee:
      state: true
      brightness: 3
      color_temp: 370
    light.living_moon:
      state: true
      brightness: 97
      color_temp: 393
  id: 38c6c0881ee34eaa806613ad1f765c56
- name: Nico Compu
  entities:
    light.front_door:
      state: 'on'
      brightness: 190
    light.countertop:
      state: 'on'
      brightness: 255
    light.couch:
      state: 'on'
      brightness: 255
    light.office: 'off'
    light.office_yee:
      state: 'on'
      brightness: 255
      color_temp: 370
    light.kitchen: 'off'
    light.living_moon: 'off'
    light.living_tortue:
      state: true
      brightness: 125
      color_temp: 370
  id: f0fa3e89a549460ea78892d81d481225
- name: Medium
  entities:
    light.office:
      state: true
      brightness: 255
    light.couch:
      state: true
      brightness: 109
    light.front_door:
      state: true
      brightness: 190
    light.countertop:
      state: true
      brightness: 142
    light.office_yee:
      state: true
      brightness: 54
      color_temp: 332
    light.living_moon:
      state: true
      brightness: 74
      color_temp: 349
    light.kitchen:
      state: true
      brightness: 171
      color_temp: 319
    light.living_tortue:
      state: true
      brightness: 23
      color_temp: 360
  id: 05e64f5fd14f4ce8b81d0eb3d7dc2f13
- name: Alone - late
  entities:
    light.office_yee: false
    light.living_tortue: false
    light.living_moon:
      state: false
    light.office_ambient_light:
      state: true
      brightness: 20
      color_temp: 324
    light.office:
      state: true
      brightness: 60
    light.couch:
      state: true
      brightness: 50
    light.countertop:
      state: true
      brightness: 50
    light.kitchen:
      state: false
  id: 3561b572438f401da811536cc1970a4d
- name: Alone - evening
  entities:
    light.kitchen:
      state: true
      brightness: 132
    light.office:
      state: true
      brightness: 255
    light.couch:
      state: true
      brightness: 102
    light.countertop:
      state: true
      brightness: 102
    light.office_yee: false
    light.office_ambient_light:
      state: true
      brightness: 59
      color_temp: 358
    light.living_moon:
      state: false
    light.living_tortue:
      state: false
  id: b2894b7fb8c4406ca9aaafad943182e8
- name: Alarm
  entities:
    light.office_yee:
      state: true
      effect: Police
      brightness: 255
    light.countertop:
      state: true
      brightness: 255
    light.kitchen:
      state: true
      brightness: 255
    light.couch:
      state: true
      brightness: 255
    light.office:
      state: true
      brightness: 255
    light.living_moon:
      state: true
      effect: Police
      brightness: 255
    light.living_tortue:
      state: true
      effect: Police
      brightness: 255
  id: 7d1241c28a1a4ee1b6cea21c548fac41
- name: Someone got home
  entities:
    light.living_tortue:
      state: true
      brightness: 23
      color_temp: 360
  id: 9e90dfea8bef40e3b1a01d9a6b6b9206
- id: '1577825052881'
  name: WFH - Evening
  entities:
    light.couch:
      assumed_state: true
      brightness: 191
      effect_list:
      - colorloop
      - night
      - white
      friendly_name: Couch
      state: 'on'
      supported_features: 61
    light.countertop:
      assumed_state: true
      brightness: 165
      effect_list:
      - colorloop
      - night
      - white
      friendly_name: Countertop
      state: 'on'
      supported_features: 61
    light.kitchen:
      brightness: 59
      color_temp: 272
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Slow Temp
      - Stop
      friendly_name: Kitchen
      hs_color:
      - 27.015
      - 41.078
      max_mireds: 370
      min_mireds: 153
      rgb_color:
      - 255
      - 197
      - 150
      state: 'on'
      supported_features: 63
      xy_color:
      - 0.441
      - 0.37
    light.kitchen_wall:
      brightness: 120
      color_temp: 370
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Slow Temp
      - Stop
      friendly_name: Kitchen Wall
      hs_color:
      - 28.391
      - 65.659
      max_mireds: 370
      min_mireds: 153
      rgb_color:
      - 255
      - 166
      - 87
      state: 'on'
      supported_features: 63
      xy_color:
      - 0.526
      - 0.387
    light.living_moon:
      brightness: 97
      color_temp: 370
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Slow Temp
      - Stop
      friendly_name: Living Moon
      hs_color:
      - 28.391
      - 65.659
      max_mireds: 370
      min_mireds: 153
      rgb_color:
      - 255
      - 166
      - 87
      state: 'on'
      supported_features: 63
      xy_color:
      - 0.526
      - 0.387
    light.living_tortue:
      brightness: 59
      color_temp: 370
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Slow Temp
      - Stop
      friendly_name: Living Tortue
      hs_color:
      - 28.391
      - 65.659
      max_mireds: 370
      min_mireds: 153
      rgb_color:
      - 255
      - 166
      - 87
      state: 'on'
      supported_features: 63
      xy_color:
      - 0.526
      - 0.387
    light.office:
      assumed_state: true
      brightness: 255
      effect_list:
      - colorloop
      - night
      - white
      friendly_name: Office
      state: 'on'
      supported_features: 61
    light.office_yee:
      brightness: 3
      color_temp: 370
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Slow Temp
      - Stop
      friendly_name: Office Yee
      hs_color:
      - 28.391
      - 65.659
      max_mireds: 370
      min_mireds: 153
      rgb_color:
      - 255
      - 166
      - 87
      state: 'on'
      supported_features: 63
      xy_color:
      - 0.526
      - 0.387
- id: '1604611667101'
  name: Vick's mix
  entities:
    light.living_moon:
      min_mireds: 153
      max_mireds: 370
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Slow Temp
      - Stop
      brightness: 84
      color_temp: 393
      hs_color:
      - 28.761
      - 70.952
      rgb_color:
      - 255
      - 160
      - 74
      xy_color:
      - 0.543
      - 0.388
      flowing: false
      friendly_name: Living Moon
      supported_features: 63
      state: 'on'
    light.living_tortue:
      min_mireds: 153
      max_mireds: 370
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Slow Temp
      - Stop
      brightness: 23
      color_temp: 360
      hs_color:
      - 28.233
      - 63.317
      rgb_color:
      - 255
      - 169
      - 93
      xy_color:
      - 0.518
      - 0.386
      flowing: false
      friendly_name: Living Tortue
      supported_features: 63
      state: 'on'
    light.hue_ambiance_lamp_1:
      min_mireds: 153
      max_mireds: 454
      friendly_name: Vick's spot
      supported_features: 43
      state: 'off'
- id: '1726195259216'
  name: Movie Living
  entities:
    light.0x00178801035353ad:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6666
      min_mireds: 150
      max_mireds: 500
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - candle
      - finish_effect
      - stop_effect
      - stop_hue_effect
      supported_color_modes:
      - color_temp
      effect:
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 2732
      color_temp: 366
      hs_color:
      - 28.327
      - 64.71
      rgb_color:
      - 255
      - 167
      - 89
      xy_color:
      - 0.524
      - 0.387
      linkquality: 98
      power_on_behavior:
      update:
        installed_version: -1
        latest_version: -1
        state:
      update_available:
      friendly_name: Living Side Lamp
      supported_features: 44
      state: 'on'
    light.0x500b91400001f081:
      supported_color_modes:
      - brightness
      color_mode: brightness
      brightness: 71
      led_intensity_off: 100
      led_intensity_on: 100
      linkquality: 185
      minimumBrightness: 5
      minimum_brightness:
      timer_seconds:
      friendly_name: Living Main Dimmer
      supported_features: 40
      state: 'on'
    number.0x500b91400001f081_timer_seconds:
      min: 0
      max: 65535
      step: 1
      mode: auto
      brightness: 71
      led_intensity_off: 100
      led_intensity_on: 100
      linkquality: 185
      minimumBrightness: 5
      minimum_brightness:
      timer_seconds:
      unit_of_measurement: s
      friendly_name: living_main_dimmer Timer seconds
      state: unknown
    number.0x500b91400001f081_led_intensity_on:
      min: 0
      max: 100
      step: 1
      mode: auto
      brightness: 71
      led_intensity_off: 100
      led_intensity_on: 100
      linkquality: 185
      minimumBrightness: 5
      minimum_brightness:
      timer_seconds:
      unit_of_measurement: '%'
      friendly_name: living_main_dimmer Led intensity on
      state: '100'
    number.0x500b91400001f081_led_intensity_off:
      min: 0
      max: 100
      step: 1
      mode: auto
      brightness: 71
      led_intensity_off: 100
      led_intensity_on: 100
      linkquality: 185
      minimumBrightness: 5
      minimum_brightness:
      timer_seconds:
      unit_of_measurement: '%'
      friendly_name: living_main_dimmer Led intensity off
      state: '100'
    number.0x500b91400001f081_minimum_brightness:
      min: 0
      max: 3000
      step: 1
      mode: auto
      brightness: 71
      led_intensity_off: 100
      led_intensity_on: 100
      linkquality: 185
      minimumBrightness: 5
      minimum_brightness:
      timer_seconds:
      friendly_name: living_main_dimmer Minimum brightness
      state: unknown
  metadata: {}
