- platform: environment_canada
  
- platform: yr
- platform: openweathermap
  name: Weather Current
  api_key: !secret openweathermap_apikey
  monitored_conditions:
  - weather
  - temperature
  - humidity
  - clouds
  - rain
  - snow  
- platform: openweathermap
  name: Weather Foreacast
  api_key: !secret openweathermap_apikey
  monitored_conditions:
  - weather
  - temperature
  - humidity
  - clouds
  - rain
  - snow  

- platform: mqtt
  name: "Raw Living Temperature"
  state_topic: "/ThermoDev/Sensor02/CurrentTemperature"
  unit_of_measurement: '°C'
  # value_template: "{{ value_json.temperature }}"

- platform: mqtt
  name: "Raw Living Humidity"
  state_topic: "/ThermoDev/Sensor02/CurrentHumidity"
  unit_of_measurement: '%'

- platform: mqtt
  name: "Living On/Off"
  state_topic: "/ThermoDev/Sensor02/CurrentState"

- platform: mqtt
  name: "Raw Office Temperature"
  state_topic: "/ThermoDev/Sensor01/CurrentTemperature"
  unit_of_measurement: '°C'
  # value_template: "{{ value_json.temperature }}"

- platform: mqtt
  name: "Raw Office Humidity"
  state_topic: "/ThermoDev/Sensor01/CurrentHumidity"
  unit_of_measurement: '%'

- platform: mqtt
  name: "Office On/Off"
  state_topic: "/ThermoDev/Sensor01/CurrentState"

- platform: template
  sensors:
    average_temperature:
      value_template: "{{ ( ( (states('sensor.living_temperature') | float ) + (states('sensor.office_temperature') | float) ) / 2 ) | round(2) }}"
      entity_id:
        - sensor.living_temperature
        - sensor.office_temperature
      friendly_name: 'Average temperature'
      unit_of_measurement: "C"
    template_montreal_temperature:
      value_template: "{{ ( (states('sensor.montreal_temperature') | float) ) | round(2) }}"
      entity_id:
        - sensor.montreal_temperature
      friendly_name: 'Montreal temperature'
      unit_of_measurement: "C"
    template_montreal_humidex:
      value_template: "{{ states('sensor.montreal_humidex') | float | round(2) }}"
      entity_id:
        - sensor.montreal_humidex
      friendly_name: 'Montreal humidex'
      unit_of_measurement: "C"
    template_average_humidity:
      value_template: "{{ ( states('sensor.office_humidity') | float + states('sensor.living_humidity') | float ) / 2 | round(2) }}"
      friendly_name: "Average humidity"
      unit_of_measurement: "%"
    template_montreal_humidity:
      value_template: "{{ states('sensor.montreal_humidity') | float | round(2) }}"
      friendly_name: "Montreal Humidity"
      unit_of_measurement: "%"

- platform: filter
  name: "Living Temperature"
  entity_id: sensor.raw_living_temperature
  filters:
  - filter: lowpass
    time_constant: 5
    precision: 2

- platform: filter
  name: "Living Humidity"
  entity_id: sensor.raw_living_humidity
  filters:
  - filter: lowpass
    time_constant: 5
    precision: 2

- platform: filter
  name: "Office Temperature"
  entity_id: sensor.raw_office_temperature
  filters:
  - filter: lowpass
    time_constant: 5
    precision: 2

- platform: filter
  name: "Office Humidity"
  entity_id: sensor.raw_office_humidity
  filters:
  - filter: lowpass
    time_constant: 5
    precision: 2

- platform: mqtt
  name: "Movement detected near bathroom"
  state_topic: /bathroom/distance/state
  value_template: '{% if ( (value|float) < 1) %}on{% else %}off{% endif %}'

- platform: mqtt
  name: "Raw Basement Temperature"
  state_topic: "basement/sensor/basement_temperature/state"
  unit_of_measurement: '°C'
  # value_template: "{{ value_json.temperature }}"

- platform: mqtt
  name: "Raw Basement Humidity"
  state_topic: "basement/sensor/basement_humidity/state"
  unit_of_measurement: '%'

- platform: filter
  name: "Basement Temperature"
  entity_id: sensor.raw_basement_temperature
  filters:
  - filter: lowpass
    window_size: 5
    precision: 2

- platform: filter
  name: "Basement Humidity"
  entity_id: sensor.raw_basement_humidity
  filters:
  - filter: range
    upper_bound: 150
  - filter: outlier
    window_size: 10
    radius: 20
    precision: 2

- platform: mqtt
  name: "Raw Basement movement"
  state_topic: "basement/binary_sensor/basement_motion/state"

- platform: mqtt
  name: "Raw Basement noise"
  state_topic: "basement/binary_sensor/basement_noise/state"


# - platform: template
#   sensors:
#     nico_moto5_battery:
#       friendly_name: Cell Nico
#       unit_of_measurement: "%"
#       value_template: '{{ states.device_tracker.nico_moto5.attributes.battery|int }}'
#       device_class: battery
