- platform: yr
- platform: openweathermap
  api_key: !secret openweathermap_apikey
  monitored_conditions:
    - weather

- platform: mqtt
  name: "Living Temperature"
  state_topic: "/ThermoDev/Sensor02/CurrentTemperature"
  unit_of_measurement: '°C'
  # value_template: "{{ value_json.temperature }}"

- platform: mqtt
  name: "Living Humidity"
  state_topic: "/ThermoDev/Sensor02/CurrentHumidity"
  unit_of_measurement: '%'

- platform: mqtt
  name: "Living On/Off"
  state_topic: "/ThermoDev/Sensor02/CurrentState"


- platform: mqtt
  name: "Office Temperature"
  state_topic: "/ThermoDev/Sensor01/CurrentTemperature"
  unit_of_measurement: '°C'
  # value_template: "{{ value_json.temperature }}"

- platform: mqtt
  name: "Office Humidity"
  state_topic: "/ThermoDev/Sensor01/CurrentHumidity"
  unit_of_measurement: '%'

- platform: mqtt
  name: "Office On/Off"
  state_topic: "/ThermoDev/Sensor01/CurrentState"

- platform: template
  sensors:
    average_temperature:
      friendly_name: "Average Temperature"
      value_template: "{{ ( ( (states('sensor.living_temperature') | float ) + (states('sensor.office_temperature') | float) ) / 2 )| float }}"
      entity_id:
        - sensor.living_temperature
        - sensor.office_temperature
      friendly_name: 'Average temperature'
      unit_of_measurement: "C"

# - platform: template
#   sensors:
#     nico_moto5_battery:
#       friendly_name: Cell Nico
#       unit_of_measurement: "%"
#       value_template: '{{ states.device_tracker.nico_moto5.attributes.battery|int }}'
#       device_class: battery
