title: My Awesome Home
views:
    # View tab title.
  - id: 0  # Automatically created id
    title: Main
    icon: mdi:home
    cards:
        # The markdown card will render markdown text.
        # The picture entity card will represent an entity with a picture
      - type: entities
        title: Main
        entities:
          - group.lights_interior
          - entity: scene.all_full
            icon: mdi:lightbulb-on-outline
          - entity: input_number.at_home_temperature_slider
            name: At home
            icon: mdi:home
          - entity: light.moesdimmer_strips
            name: "Living dimmer"
          - entity: light.moesdimmer02
            name: "Office dimmer"
          
      - type: glance
        entities:
        - entity: scene.all_full
          name: All full
          icon: mdi:lightbulb-on-outline
        - entity: scene.chillin
          name: Chillin
        - entity: scene.morning
          name: Morning
        - entity: scene.movies
          name: Movies

      - type: horizontal-stack
        cards:
        - type: gauge
          entity: sensor.average_temperature
          name: Home
          min: 16
          max: 28
          unit: C
          severity:
        - type: gauge
          entity: sensor.living_temperature
          name: Living
          min: 16
          max: 28
          unit: C
        - type: gauge
          entity: sensor.office_temperature
          name: Office
          min: 16
          max: 28
          unit: C


  - id: 1
    title: Lights
    icon: mdi:lightbulb
    cards:
    - type: glance
      title: Global
      entities:
      - entity: group.all_lights
        name: "All"
    - type: entities
      title: "Office"
      icon: mdi:desktop-classic
      entities:
      - light.office
      - light.office_yee
      - light.office_ceiling
    - type: entities
      icon: mdi:fridge-outline
      title: "Kitchen"
      entities:
      - light.countertop
      - light.kitchen
    - type: entities
      title: "Living"
      entities:
      - light.couch
      - light.living_moon
    - type: horizontal-stack
      cards:
      - type: entities
        entities:
        - entity: group.all_lights
        name: "All"      
      - type: light
        entity: light.moesdimmer01
        name: "Dimmer Leds"
      - type: light
        entity: light.moesdimmer02
        name: "Dimmer Lamps"

  - id: 2
    title: Settings
    icon: mdi:thermometer
    cards:
      - type: glance
        entities:
        - entity: sensor.living_temperature
          name: Living
          icon: mdi:thermometer
        - entity: binary_sensor.living_heater_state
          name: Living
        - entity: sensor.office_temperature
          name: Office
          icon: mdi:thermometer
        - entity: binary_sensor.office_heater_state
          name: Office

      - type: entities
        title: Temperature settings
        entities:
        - entity: input_number.at_home_temperature_slider
          name: At home
          icon: mdi:home
        - entity: input_number.at_home_sleeping
          name: Sleeping
          icon: mdi:sleep
        - entity: input_number.home_alone_temperature_slider
          name: When alone
          icon: mdi:home-lock
      - type: entities
        # Title of the entities card
        title: Temperature
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - input_number.living_temperature_slider
          - input_number.office_temperature_slider  
      - type: history-graph
        hours_to_show: 12
        refresh_interval: 60
        title: History
        entities:
        - entity: sensor.living_temperature
          name: Living ºC
          icon: mdi:thermometer
        - entity: binary_sensor.living_heater_state
          name: Living
        - entity: sensor.office_temperature
          name: Office ºC
          icon: mdi:thermometer
        - entity: binary_sensor.office_heater_state
          name: Office         
        - entity: input_number.office_temperature_slider
          name: Office Set
          icon: mdi:thermometer
        - entity: input_number.living_temperature_slider
          name: Kitchen Set
          icon: mdi:thermometer                     

  - id: 3
    title: Presence
    icon: mdi:home-assistant
    cards:
      - type: entity-filter
        entities:
          - entity: device_tracker.nico_moto5
            name: Nico Moto5
          - entity: device_tracker.vsmbr_phone
            name: Vick
          - entity: device_tracker.nico_moto5_ping
            name: Nico
        state_filter:
          - 'home'
        card:
          type: glance
          title: People at home
  - id: 4
    title: Cameras
    icon: mdi:camcorder
    cards:
    - type: picture-glance
      entities:
      - camera.door
      title: Door
      camera_image: camera.door
    - type: picture-glance
      entities:
      - light.countertop
      - light.kitchen
      title: Kitchen
      camera_image: camera.kitchen
