title: My Awesome Home
views:

  - id: 1
    title: Lights
    icon: mdi:home
    cards:
    - type: horizontal-stack
      cards:    
      - type: entity-button
        entity: group.all_lights
        name: Lighs on
        icon: mdi:lightbulb-on-outline
        tap_action:
          action: call-service
          service: light.turn_on
          service_data:
            entity_id:  group.all_lights
      - type: entity-button
        name: Sleep
        entity: group.all_lights
        icon: mdi:hotel
        tap_action:
          action: call-service
          service: light.turn_off
          service_data:
            entity_id:  group.all_lights
      - type: entity-button
        entity: scene.movies
        tap_action:
          action: call-service
          service: scene.turn_on
          service_data:
            entity_id:  scene.movies
        hold_action:
          action: call-service
          service: light.turn_on
          service_data:
            entity_id:  group.all_lights
    - type: glance
      entities:
      - entity: sensor.living_temperature
        name: Living
        icon: mdi:thermometer
      - entity: binary_sensor.living_heater_state
        name: Living
      - entity: sensor.office_temperature
        name: Office
        icon: mdi:thermometer
      - entity: binary_sensor.office_heater_state
        name: Office
    - type: horizontal-stack
      cards:
      - type: light
        entity: light.moesdimmerliving
        name: "Strips"
      - type: light
        entity: light.moesdimmeroffice
        name: "Lamps"
    - type: entities
      title: "Office"
      icon: mdi:desktop-classic
      entities:
      - light.office
      - light.office_yee
    - type: entities
      icon: mdi:fridge-outline
      title: "Kitchen"
      entities:
      - light.countertop
      - light.kitchen
    - type: entities
      title: "Living"
      entities:
      - light.couch
      - light.living_moon
    - type: horizontal-stack
      cards:
      - type: gauge
        entity: sensor.average_temperature
        title: Home Temperature
      - type: history-graph
        hours_to_show: 6
        refresh_interval: 60
        entities:
        - entity: sensor.average_temperature
          name: C
          icon: mdi:home     

  - id: 2
    title: Lights
    icon: mdi:lightbulb
    cards:
    - type: horizontal-stack
      cards:    
      - type: entity-button
        entity: group.all_lights
        name: Lighs on
        icon: mdi:lightbulb-on-outline
        tap_action:
          action: call-service
          service: light.turn_on
          service_data:
            entity_id:  group.all_lights
      - type: entity-button
        name: Sleep
        entity: group.all_lights
        icon: mdi:hotel
        tap_action:
          action: call-service
          service: light.turn_off
          service_data:
            entity_id:  group.all_lights
      - type: entity-button
        entity: scene.movies
        tap_action:
          action: call-service
          service: scene.turn_on
          service_data:
            entity_id:  scene.movies
        hold_action:
          action: call-service
          service: light.turn_on
          service_data:
            entity_id:  group.all_lights
    - type: entities
      title: "Office"
      icon: mdi:desktop-classic
      entities:
      - light.office
      - light.office_yee
    - type: entities
      icon: mdi:fridge-outline
      title: "Kitchen"
      entities:
      - light.countertop
      - light.kitchen
    - type: entities
      title: "Living"
      entities:
      - light.couch
      - light.living_moon
    - type: horizontal-stack
      cards:
      - type: light
        entity: light.moesdimmerliving
        name: "Strips"
      - type: light
        entity: light.moesdimmeroffice
        name: "Lamps"

  - id: 2
    title: Settings
    icon: mdi:thermometer
    cards:
      - type: glance
        entities:
        - entity: sensor.living_temperature
          name: Living
          icon: mdi:thermometer
        - entity: binary_sensor.living_heater_state
          name: Living
        - entity: sensor.office_temperature
          name: Office
          icon: mdi:thermometer
        - entity: binary_sensor.office_heater_state
          name: Office
      - type: entities
        title: Temperature settings
        entities:
        - entity: input_number.at_home_temperature_slider
          name: At home
          icon: mdi:home
        - entity: input_number.at_home_sleeping
          name: Sleeping
          icon: mdi:sleep
        - entity: input_number.home_alone_temperature_slider
          name: When alone
          icon: mdi:home-lock
      - type: entities
        # Title of the entities card
        title: Temperature
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - input_number.living_temperature_slider
          - input_number.office_temperature_slider  
      - type: history-graph
        hours_to_show: 12
        refresh_interval: 60
        entities:
        - entity: sensor.living_temperature
          name: Living ºC
          icon: mdi:thermometer
        - entity: binary_sensor.living_heater_state
          name: Living
        - entity: sensor.office_temperature
          name: Office ºC
          icon: mdi:thermometer
        - entity: binary_sensor.office_heater_state
          name: Office         
        - entity: input_number.office_temperature_slider
          name: Office Set
          icon: mdi:thermometer
        - entity: input_number.living_temperature_slider
          name: Kitchen Set
          icon: mdi:thermometer

  - id: 3
    title: Presence
    icon: mdi:home-assistant
    cards:
      - type: entity-filter
        entities:
          - entity: device_tracker.nico_moto5
            name: Nico Moto5
          - entity: device_tracker.vsmbr_phone
            name: Vick
          - entity: device_tracker.nico_moto5_ping
            name: Nico
        state_filter:
          - 'home'
        card:
          type: glance
          title: People at home
  - id: 4
    title: Cameras
    icon: mdi:camcorder
    cards:
    - type: picture-glance
      entities:
      - camera.door
      title: Door
      camera_image: camera.door
    - type: picture-glance
      entities:
      - light.countertop
      - light.kitchen
      title: Kitchen
      camera_image: camera.kitchen
