title: The 1961
views:
  - id: 1
    title: Lights
    icon: mdi:home
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entity-button
                name: Sleep
                entity: group.lights_interior
                icon: mdi:bed
                tap_action:
                  action: call-service
                  service: light.turn_off
                  service_data:
                    entity_id: group.lights_interior
              - type: entity-button
                entity: scene.movies
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.movies
                hold_action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: group.all_lights
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.average_temperature
                name: Home Temperature
                icon: mdi:home
                graph: true
          - type: entities
            title: "Living"
            entities:
              - light.couch
              - light.living_moon
              - light.living_tortue
          - type: entity-filter
            entities:
              - entity: binary_sensor.living_heater_state
                name: Living
              - entity: binary_sensor.office_heater_state
                name: Office
              - entity: sensor.raw_ac_vibration_sensor
                name: A/C
            state_filter:
              - "on"
            card:
              type: glance
              title: Power consumption
            show_empty: false
      - type: vertical-stack
        cards:
          - type: entities
            title: "Office"
            icon: mdi:desktop-classic
            entities:
              - light.office_yee
              - light.officedimmer
              - light.office_back_lamp
          - type: entities
            title: "Bedroom"
            icon: mdi:desktop-classic
            entities:
              - light.downlight_01_downlight_01
              - light.hue_ambiance_candle_1
          - type: entities
            icon: mdi:fridge-outline
            title: "Kitchen"
            entities:
              - light.countertop
              - light.kitchen_main
              - light.kitchen_lamp
      - type: vertical-stack
        cards:
          - type: entity-filter
            entities:
              - entity: device_tracker.nico_moto5
                name: Nico Moto5
              - entity: device_tracker.vsmbr_phone
                name: Vick
              - entity: device_tracker.nico_moto5_ping
                name: Nico
            state_filter:
              - "home"
            show_empty: false
            card:
              type: glance
          - type: horizontal-stack
            cards:
              - type: picture-glance
                entities:
                  - camera.door
                title: Door
                camera_image: camera.door
              - type: picture-glance
                entities:
                  - light.countertop
                  - light.kitchen_main
                  - light.kitchen_lamp
                title: Kitchen
                camera_image: camera.kitchen
          - type: weather-forecast
            entity: weather.longueuil
      - type: entities
        title: Scenes
        entities:
          - entity: scene.all_full
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.all_full
          - entity: scene.alone_evening
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.alone_evening
          - entity: scene.alone_late
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.alone_late
          - entity: scene.chillin
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.chillin
          - entity: scene.movies
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.movies
          - entity: scene.nico_compu
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.nico_compu
          - entity: scene.red_ambient
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.red_ambient
          - entity: scene.someone_got_home
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.someone_got_home
          - entity: scene.medium
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.medium

  - id: 2
    title: Lights
    icon: mdi:lightbulb
    cards:
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: group.all_lights
            name: Lighs on
            icon: mdi:lightbulb-on-outline
            tap_action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: group.all_lights
          - type: entity-button
            name: Sleep
            entity: group.lights_interior
            icon: mdi:bed
            tap_action:
              action: call-service
              service: light.turn_off
              service_data:
                entity_id: group.lights_interior
          - type: entity-button
            entity: scene.movies
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.movies
            hold_action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: group.all_lights
      - type: entities
        title: "Office"
        icon: mdi:desktop-classic
        entities:
          - light.office
          - light.office_yee
          - light.officedimmer
          - light.office_back_lamp
      - type: entities
        icon: mdi:fridge-outline
        title: "Kitchen"
        entities:
          - light.countertop
          - light.kitchen_main
          - light.kitchen_lamp
      - type: entities
        title: "Living"
        entities:
          - light.couch
          - light.living_moon
          - light.living_tortue


  - id: 5
    title: Cameras
    icon: mdi:camcorder
    cards:
      - type: picture-glance
        entities:
          - camera.door
        title: Door
        camera_image: camera.door
      - type: picture-glance
        entities:
          - light.countertop
          - light.kitchen
          - light.kitchen_lamp
        title: Kitchen
        camera_image: camera.kitchen
  - id: 6
    title: Basement
    cards:
      - type: history-graph
        title: 12 Hours
        hours_to_show: 12
        refresh_interval: 60
        entities:
          - entity: sensor.basement_temperature
            name: Basement ºC
            icon: mdi:thermometer
          - entity: sensor.basement_humidity
            name: Basement H.
            icon: mdi:thermometer
      - type: entities
        entities:
          - sensor.basement_humidity_2
          - binary_sensor.basement_motion
          - binary_sensor.basement_noise
          - sensor.basement_temperature_2
      - type: entities
        entities:
          - sensor.sonoff_status
      - type: light
        entity: light.sonoff


resources:
  # Note: the `community_plugin` root and `type` is `module`. Also, no `?v=` query string as HACS
  #   will make sure that the most recent version is always loaded.
  - url: /hacsfiles/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js
    type: module