devices:
  192.168.2.243:
    name: Kitchen Lamp
    transition: 100
    use_music_mode: False #(defaults to False)
    save_on_change: false #(defaults to false)
    model: color2
  192.168.1.202:
    name: Office Yee
    transition: 100
    use_music_mode: False #(defaults to False)
    save_on_change: false #(defaults to false)
    model: color2
  192.168.1.203:
    name: Living Moon
    transition: 100
    use_music_mode: False #(defaults to False)
    save_on_change: false #(defaults to false)
    model: color2
  192.168.1.221:
    name: Living Tortue
    transition: 100
    model: color2
  192.168.1.135:
    name: Office Back Lamp
    transition: 100
    model: color2
