- name: Work
  latitude: 45.539926
  longitude: -73.655023
  radius: 50
  icon: mdi:school
- name: Home
  latitude: 45.5303786
  longitude: -73.5545572
  radius: 100
  icon: mdi:home
- name: Around home
  latitude: 45.5303786
  longitude: -73.5545572
  radius: 450
  icon: mdi:home
